/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AuthCheckEndpointResponse;
import com.odditt.apiclient.model.AuthCreateAPIKeyRequest;
import com.odditt.apiclient.model.AuthCreateAPIKeyResponse;
import com.odditt.apiclient.model.AuthCreateSecretResponse;
import com.odditt.apiclient.model.AuthErrorResponse;
import com.odditt.apiclient.model.AuthListAPIKeysResponse;
import com.odditt.apiclient.model.AuthListSecretsResponse;
import com.odditt.apiclient.model.AuthSetCheckEndpointRequest;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.odditt.apiclient.model.V1AccountApiKeysKeyCodeDelete409Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Disabled
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * List own API keys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountApiKeysGetTest() throws ApiException {
        AuthListAPIKeysResponse response = api.v1AccountApiKeysGet();
        // TODO: test validations
    }

    /**
     * Deactivate an API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountApiKeysKeyCodeDeleteTest() throws ApiException {
        UUID keyCode = null;
        api.v1AccountApiKeysKeyCodeDelete(keyCode);
        // TODO: test validations
    }

    /**
     * Create a new API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountApiKeysPostTest() throws ApiException {
        AuthCreateAPIKeyRequest authCreateAPIKeyRequest = null;
        AuthCreateAPIKeyResponse response = api.v1AccountApiKeysPost(authCreateAPIKeyRequest);
        // TODO: test validations
    }

    /**
     * Delete the check endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountCheckEndpointDeleteTest() throws ApiException {
        api.v1AccountCheckEndpointDelete();
        // TODO: test validations
    }

    /**
     * Get the configured check endpoint
     *
     * Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountCheckEndpointGetTest() throws ApiException {
        AuthCheckEndpointResponse response = api.v1AccountCheckEndpointGet();
        // TODO: test validations
    }

    /**
     * Set the check endpoint (upsert)
     *
     * Stores or updates the URL, method and bearer token used to quote flows against the client&#39;s own service. A single configuration exists per client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountCheckEndpointPostTest() throws ApiException {
        AuthSetCheckEndpointRequest authSetCheckEndpointRequest = null;
        AuthCheckEndpointResponse response = api.v1AccountCheckEndpointPost(authSetCheckEndpointRequest);
        // TODO: test validations
    }

    /**
     * Get own client configuration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountConfigGetTest() throws ApiException {
        api.v1AccountConfigGet();
        // TODO: test validations
    }

    /**
     * Create a new client secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountSecretPostTest() throws ApiException {
        AuthCreateSecretResponse response = api.v1AccountSecretPost();
        // TODO: test validations
    }

    /**
     * List own client secrets
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountSecretsGetTest() throws ApiException {
        AuthListSecretsResponse response = api.v1AccountSecretsGet();
        // TODO: test validations
    }

    /**
     * Delete a client secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountSecretsSecretCodeDeleteTest() throws ApiException {
        UUID secretCode = null;
        api.v1AccountSecretsSecretCodeDelete(secretCode);
        // TODO: test validations
    }

    /**
     * Get own usage stats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountUsageGetTest() throws ApiException {
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        api.v1AccountUsageGet(startDate, endDate);
        // TODO: test validations
    }

}
