/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AuthErrorResponse;
import com.odditt.apiclient.model.AuthOAuthLoginRequest;
import com.odditt.apiclient.model.AuthRefreshRequest;
import com.odditt.apiclient.model.AuthTokenPair;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Disabled
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * Login with API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AuthLoginPostTest() throws ApiException {
        String xAPIKey = null;
        AuthTokenPair response = api.v1AuthLoginPost(xAPIKey);
        // TODO: test validations
    }

    /**
     * Refresh tokens
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AuthRefreshPostTest() throws ApiException {
        AuthRefreshRequest authRefreshRequest = null;
        AuthTokenPair response = api.v1AuthRefreshPost(authRefreshRequest);
        // TODO: test validations
    }

    /**
     * OAuth login (client credentials)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1OauthLoginPostTest() throws ApiException {
        AuthOAuthLoginRequest authOAuthLoginRequest = null;
        AuthTokenPair response = api.v1OauthLoginPost(authOAuthLoginRequest);
        // TODO: test validations
    }

    /**
     * OAuth refresh
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1OauthRefreshPostTest() throws ApiException {
        AuthRefreshRequest authRefreshRequest = null;
        AuthTokenPair response = api.v1OauthRefreshPost(authRefreshRequest);
        // TODO: test validations
    }

}
