/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import java.io.File;
import com.odditt.apiclient.model.TrendsErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HistoricalApi
 */
@Disabled
public class HistoricalApiTest {

    private final HistoricalApi api = new HistoricalApi();

    /**
     * List historical odds events (paginated)
     *
     * Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive &#x60;403 Forbidden&#x60;. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1HistoricalEventsGetTest() throws ApiException {
        String schemaVersion = null;
        Long sportId = null;
        Long leagueId = null;
        Long teamId = null;
        String startDate = null;
        String endDate = null;
        Long page = null;
        Long pageSize = null;
        Object response = api.v1HistoricalEventsGet(schemaVersion, sportId, leagueId, teamId, startDate, endDate, page, pageSize);
        // TODO: test validations
    }

    /**
     * Download a per-event historical odds file
     *
     * Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The &#x60;sha256&#x60; of the bytes-at-rest is exposed as a strong &#x60;ETag&#x60;. Clients can short-circuit with &#x60;If-None-Match&#x60; to receive &#x60;304 Not Modified&#x60;. &#x60;Range&#x60; requests are forwarded upstream and &#x60;206 Partial Content&#x60; responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1HistoricalOddsEventIdExtGetTest() throws ApiException {
        Long eventId = null;
        String ext = null;
        String schemaVersion = null;
        Object response = api.v1HistoricalOddsEventIdExtGet(eventId, ext, schemaVersion);
        // TODO: test validations
    }

}
