/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AffiliateErrorResponse;
import java.util.UUID;
import com.odditt.apiclient.model.V1AffiliatesLinksBulkDeactivatePostRequest;
import com.odditt.apiclient.model.V1AffiliatesLinksBulkPatchRequest;
import com.odditt.apiclient.model.V1AffiliatesLinksBulkPost202Response;
import com.odditt.apiclient.model.V1AffiliatesLinksPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LinksApi
 */
@Disabled
public class LinksApiTest {

    private final LinksApi api = new LinksApi();

    /**
     * Bulk deactivate links by filter
     *
     * Soft-deletes all links matching a filter (e.g. a state goes offline).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksBulkDeactivatePostTest() throws ApiException {
        V1AffiliatesLinksBulkDeactivatePostRequest v1AffiliatesLinksBulkDeactivatePostRequest = null;
        Object response = api.v1AffiliatesLinksBulkDeactivatePost(v1AffiliatesLinksBulkDeactivatePostRequest);
        // TODO: test validations
    }

    /**
     * Bulk patch links by filter
     *
     * Applies a patch to all links matching a filter (e.g. rewrite all FanDuel-NJ URLs on a domain change).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksBulkPatchTest() throws ApiException {
        V1AffiliatesLinksBulkPatchRequest v1AffiliatesLinksBulkPatchRequest = null;
        Object response = api.v1AffiliatesLinksBulkPatch(v1AffiliatesLinksBulkPatchRequest);
        // TODO: test validations
    }

    /**
     * Bulk create/upsert links (JSON or CSV)
     *
     * Upserts many links idempotently on the natural key. Accepts a JSON array of row objects or a text/csv body (header row). Per-row errors never fail the batch. Use ?dry_run&#x3D;true to validate without persisting.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksBulkPostTest() throws ApiException {
        List<Object> requestBody = null;
        Boolean dryRun = null;
        Boolean async = null;
        Object response = api.v1AffiliatesLinksBulkPost(requestBody, dryRun, async);
        // TODO: test validations
    }

    /**
     * List async bulk jobs
     *
     * Recent async bulk jobs for the authenticated client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksJobsGetTest() throws ApiException {
        Object response = api.v1AffiliatesLinksJobsGet();
        // TODO: test validations
    }

    /**
     * Poll an async bulk job
     *
     * Status, counts, and per-row errors for one async bulk job. Poll until status is \&quot;completed\&quot; or \&quot;failed\&quot;. Scoped to the authenticated client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksJobsJobIdGetTest() throws ApiException {
        UUID jobId = null;
        Object response = api.v1AffiliatesLinksJobsJobIdGet(jobId);
        // TODO: test validations
    }

    /**
     * Create or upsert a single link
     *
     * Creates a link, or updates the existing one on the natural key (operator + geography + category + campaign + label). Resolves operator, country, and region at write time; unresolvable codes return 422.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksPostTest() throws ApiException {
        V1AffiliatesLinksPostRequest v1AffiliatesLinksPostRequest = null;
        Object response = api.v1AffiliatesLinksPost(v1AffiliatesLinksPostRequest);
        // TODO: test validations
    }

}
