/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AffiliateErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LookupsApi
 */
@Disabled
public class LookupsApiTest {

    private final LookupsApi api = new LookupsApi();

    /**
     * Affiliate networks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLookupsAffiliateNetworksGetTest() throws ApiException {
        Object response = api.v1AffiliatesLookupsAffiliateNetworksGet();
        // TODO: test validations
    }

    /**
     * Offer categories
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLookupsOfferCategoriesGetTest() throws ApiException {
        Object response = api.v1AffiliatesLookupsOfferCategoriesGet();
        // TODO: test validations
    }

    /**
     * Operator jurisdictions
     *
     * Where we believe an operator is live. Informational only — not an upload gate.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLookupsOperatorJurisdictionsGetTest() throws ApiException {
        Long operatorId = null;
        String countryCode = null;
        Object response = api.v1AffiliatesLookupsOperatorJurisdictionsGet(operatorId, countryCode);
        // TODO: test validations
    }

    /**
     * Operators
     *
     * Paginated list of operators, optionally filtered by a free-text search term.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLookupsOperatorsGetTest() throws ApiException {
        String search = null;
        Integer page = null;
        Integer pageSize = null;
        Object response = api.v1AffiliatesLookupsOperatorsGet(search, page, pageSize);
        // TODO: test validations
    }

}
