/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.V1OddsUpcomingOddsByEventPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OddsApi
 */
@Disabled
public class OddsApiTest {

    private final OddsApi api = new OddsApi();

    /**
     * Get upcoming odds by event
     *
     * Returns paginated betting market positions for a specific upcoming event, optionally filtered by operator.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1OddsUpcomingOddsByEventPostTest() throws ApiException {
        V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest = null;
        Object response = api.v1OddsUpcomingOddsByEventPost(v1OddsUpcomingOddsByEventPostRequest);
        // TODO: test validations
    }

}
