/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AffiliateErrorResponse;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportingApi
 */
@Disabled
public class ReportingApiTest {

    private final ReportingApi api = new ReportingApi();

    /**
     * Impression/click rollups
     *
     * Per-link, per-day impression and click counts for the authenticated client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksClicksGetTest() throws ApiException {
        LocalDate startDate = null;
        LocalDate endDate = null;
        Long operatorId = null;
        String countryCode = null;
        String subnationalRegionCode = null;
        String offerCampaign = null;
        String offerLabel = null;
        Object response = api.v1AffiliatesLinksClicksGet(startDate, endDate, operatorId, countryCode, subnationalRegionCode, offerCampaign, offerLabel);
        // TODO: test validations
    }

    /**
     * Inventory counts
     *
     * Active/inactive link counts grouped by the requested dimension.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesLinksInventorySummaryGetTest() throws ApiException {
        String groupBy = null;
        Object response = api.v1AffiliatesLinksInventorySummaryGet(groupBy);
        // TODO: test validations
    }

}
