/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.AffiliateErrorResponse;
import com.odditt.apiclient.model.V1AffiliatesEventsPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TelemetryApi
 */
@Disabled
public class TelemetryApiTest {

    private final TelemetryApi api = new TelemetryApi();

    /**
     * Log an impression or click
     *
     * Fire-and-forget telemetry. Records one impression (card render) or click (deeplink tap). Returns 202 on accept; never blocks the widget&#39;s click-out.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AffiliatesEventsPostTest() throws ApiException {
        V1AffiliatesEventsPostRequest v1AffiliatesEventsPostRequest = null;
        api.v1AffiliatesEventsPost(v1AffiliatesEventsPostRequest);
        // TODO: test validations
    }

}
