/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.model.TrendsErrorResponse;
import com.odditt.apiclient.model.TrendsQuoteFlowItem;
import com.odditt.apiclient.model.TrendsQuoteItemResult;
import com.odditt.apiclient.model.TrendsQuoteSandboxRequest;
import com.odditt.apiclient.model.TrendsQuoteSandboxResponse;
import com.odditt.apiclient.model.TrendsWidgetEventRequest;
import com.odditt.apiclient.model.TrendsWidgetEventResponse;
import com.odditt.apiclient.model.V1TrendsByBettingMarketPositionPostRequest;
import com.odditt.apiclient.model.V1TrendsFlowsByIdPostRequest;
import com.odditt.apiclient.model.V1TrendsFlowsPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrendsApi
 */
@Disabled
public class TrendsApiTest {

    private final TrendsApi api = new TrendsApi();

    /**
     * Get flows by betting market position IDs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsByBettingMarketPositionPostTest() throws ApiException {
        V1TrendsByBettingMarketPositionPostRequest v1TrendsByBettingMarketPositionPostRequest = null;
        Object response = api.v1TrendsByBettingMarketPositionPost(v1TrendsByBettingMarketPositionPostRequest);
        // TODO: test validations
    }

    /**
     * Get fact flow graph data
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowGraphDataFactFlowIdGetTest() throws ApiException {
        Long factFlowId = null;
        Object response = api.v1TrendsFlowGraphDataFactFlowIdGet(factFlowId);
        // TODO: test validations
    }

    /**
     * Get flow tooltip payload
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowTooltipFlowTypeFlowIdGetTest() throws ApiException {
        String flowType = null;
        Long flowId = null;
        Object response = api.v1TrendsFlowTooltipFlowTypeFlowIdGet(flowType, flowId);
        // TODO: test validations
    }

    /**
     * Get flows by ids
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowsByIdPostTest() throws ApiException {
        V1TrendsFlowsByIdPostRequest v1TrendsFlowsByIdPostRequest = null;
        Object response = api.v1TrendsFlowsByIdPost(v1TrendsFlowsByIdPostRequest);
        // TODO: test validations
    }

    /**
     * Get flows (paginated)
     *
     * Same parameters as mixed-flows but returns non-mixed (single-type) flows. Uses the same underlying request model.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowsPostTest() throws ApiException {
        V1TrendsFlowsPostRequest v1TrendsFlowsPostRequest = null;
        Object response = api.v1TrendsFlowsPost(v1TrendsFlowsPostRequest);
        // TODO: test validations
    }

    /**
     * Quote a batch of flows against the caller&#39;s configured check endpoint
     *
     * Accepts a JSON array of 1..50 flow specifications and, for each one, forwards a hydrated payload to the URL the caller has registered under &#x60;/v1/account/check-endpoint&#x60;. Outbound calls run in parallel; the response is a JSON array with one entry per input item, in input order. Per-item failures are encoded in each entry&#39;s &#x60;status&#x60; (and &#x60;body&#x60;) so one bad operator response does not poison the others. Batch-level failures map to HTTP 4xx without an array body — 412 when the caller has not configured a check endpoint, 422 on validation failure.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowsQuotePostTest() throws ApiException {
        List<TrendsQuoteFlowItem> trendsQuoteFlowItem = null;
        List<TrendsQuoteItemResult> response = api.v1TrendsFlowsQuotePost(trendsQuoteFlowItem);
        // TODO: test validations
    }

    /**
     * Mock operator pricing endpoint — for sandbox / development use
     *
     * Drop-in stand-in for a real operator&#39;s pricing endpoint. Accepts ONE hydrated pricing payload (the exact shape that /v1/trends/flows/quote POSTs to a configured check endpoint) and returns synthetic pricing- response data with deterministic &#x60;button_payload&#x60; values and randomly- injected failure modes (~15% rate). Integrators wire this URL into /v1/account/check-endpoint as &#x60;url&#x60; to round-trip the widget call entirely on platform infrastructure without a real operator. Not for production traffic.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsFlowsQuoteSandboxPostTest() throws ApiException {
        TrendsQuoteSandboxRequest trendsQuoteSandboxRequest = null;
        TrendsQuoteSandboxResponse response = api.v1TrendsFlowsQuoteSandboxPost(trendsQuoteSandboxRequest);
        // TODO: test validations
    }

    /**
     * Get leagues with available flows
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsLeaguesWithAvailableFlowsGetTest() throws ApiException {
        Long sportId = null;
        String sportKey = null;
        Object response = api.v1TrendsLeaguesWithAvailableFlowsGet(sportId, sportKey);
        // TODO: test validations
    }

    /**
     * Get mixed flows (paginated)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsMixedFlowsPostTest() throws ApiException {
        V1TrendsFlowsPostRequest v1TrendsFlowsPostRequest = null;
        Object response = api.v1TrendsMixedFlowsPost(v1TrendsFlowsPostRequest);
        // TODO: test validations
    }

    /**
     * Submit a widget telemetry event
     *
     * Records a single client-side widget interaction (impression, click, dwell, or cart action) for analytics. Accepts a typed envelope &#x60;{event_type, mode, event_body}&#x60;: &#x60;event_type&#x60; is a closed enum naming the interaction, optional &#x60;mode&#x60; describes the widget mode, and &#x60;event_body&#x60; is an arbitrary JSON object whose shape depends on the event. Available only to widget API keys. Fire-and-forget: returns &#x60;202 Accepted&#x60; once the event is queued; the response does not guarantee durable storage.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TrendsWidgetEventPostTest() throws ApiException {
        TrendsWidgetEventRequest trendsWidgetEventRequest = null;
        TrendsWidgetEventResponse response = api.v1TrendsWidgetEventPost(trendsWidgetEventRequest);
        // TODO: test validations
    }

}
