/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthListAPIKeysResponseApiKeysInner
 */
public class AuthListAPIKeysResponseApiKeysInnerTest {
    private final AuthListAPIKeysResponseApiKeysInner model = new AuthListAPIKeysResponseApiKeysInner();

    /**
     * Model tests for AuthListAPIKeysResponseApiKeysInner
     */
    @Test
    public void testAuthListAPIKeysResponseApiKeysInner() {
        // TODO: test AuthListAPIKeysResponseApiKeysInner
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'keyCode'
     */
    @Test
    public void keyCodeTest() {
        // TODO: test keyCode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'widget'
     */
    @Test
    public void widgetTest() {
        // TODO: test widget
    }

}
