/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthTokenPair
 */
public class AuthTokenPairTest {
    private final AuthTokenPair model = new AuthTokenPair();

    /**
     * Model tests for AuthTokenPair
     */
    @Test
    public void testAuthTokenPair() {
        // TODO: test AuthTokenPair
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    public void accessTokenTest() {
        // TODO: test accessToken
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'tokenType'
     */
    @Test
    public void tokenTypeTest() {
        // TODO: test tokenType
    }

}
