/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TrendsWidgetEventRequest
 */
public class TrendsWidgetEventRequestTest {
    private final TrendsWidgetEventRequest model = new TrendsWidgetEventRequest();

    /**
     * Model tests for TrendsWidgetEventRequest
     */
    @Test
    public void testTrendsWidgetEventRequest() {
        // TODO: test TrendsWidgetEventRequest
    }

    /**
     * Test the property 'eventBody'
     */
    @Test
    public void eventBodyTest() {
        // TODO: test eventBody
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

}
