/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TrendsQuoteSandboxResponse
 */
public class TrendsQuoteSandboxResponseTest {
    private final TrendsQuoteSandboxResponse model = new TrendsQuoteSandboxResponse();

    /**
     * Model tests for TrendsQuoteSandboxResponse
     */
    @Test
    public void testTrendsQuoteSandboxResponse() {
        // TODO: test TrendsQuoteSandboxResponse
    }

    /**
     * Test the property 'americanOddsValue'
     */
    @Test
    public void americanOddsValueTest() {
        // TODO: test americanOddsValue
    }

    /**
     * Test the property 'buttonPayload'
     */
    @Test
    public void buttonPayloadTest() {
        // TODO: test buttonPayload
    }

    /**
     * Test the property 'decimalOddsValue'
     */
    @Test
    public void decimalOddsValueTest() {
        // TODO: test decimalOddsValue
    }

    /**
     * Test the property 'eventBettingMarketPositionMaps'
     */
    @Test
    public void eventBettingMarketPositionMapsTest() {
        // TODO: test eventBettingMarketPositionMaps
    }

    /**
     * Test the property 'flowId'
     */
    @Test
    public void flowIdTest() {
        // TODO: test flowId
    }

    /**
     * Test the property 'flowType'
     */
    @Test
    public void flowTypeTest() {
        // TODO: test flowType
    }

    /**
     * Test the property 'fractionalOddsValue'
     */
    @Test
    public void fractionalOddsValueTest() {
        // TODO: test fractionalOddsValue
    }

    /**
     * Test the property 'isCombinable'
     */
    @Test
    public void isCombinableTest() {
        // TODO: test isCombinable
    }

    /**
     * Test the property 'oddsImpliedProbability'
     */
    @Test
    public void oddsImpliedProbabilityTest() {
        // TODO: test oddsImpliedProbability
    }

    /**
     * Test the property 'parlayFailureReason'
     */
    @Test
    public void parlayFailureReasonTest() {
        // TODO: test parlayFailureReason
    }

    /**
     * Test the property 'payoutMultiplier'
     */
    @Test
    public void payoutMultiplierTest() {
        // TODO: test payoutMultiplier
    }

}
