/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1AccountApiKeysKeyCodeDelete409Response
 */
public class V1AccountApiKeysKeyCodeDelete409ResponseTest {
    private final V1AccountApiKeysKeyCodeDelete409Response model = new V1AccountApiKeysKeyCodeDelete409Response();

    /**
     * Model tests for V1AccountApiKeysKeyCodeDelete409Response
     */
    @Test
    public void testV1AccountApiKeysKeyCodeDelete409Response() {
        // TODO: test V1AccountApiKeysKeyCodeDelete409Response
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

}
