/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1AffiliatesLinksBulkPost202Response
 */
public class V1AffiliatesLinksBulkPost202ResponseTest {
    private final V1AffiliatesLinksBulkPost202Response model = new V1AffiliatesLinksBulkPost202Response();

    /**
     * Model tests for V1AffiliatesLinksBulkPost202Response
     */
    @Test
    public void testV1AffiliatesLinksBulkPost202Response() {
        // TODO: test V1AffiliatesLinksBulkPost202Response
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'pollUrl'
     */
    @Test
    public void pollUrlTest() {
        // TODO: test pollUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'submittedRows'
     */
    @Test
    public void submittedRowsTest() {
        // TODO: test submittedRows
    }

}
