/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1AffiliatesDealsPostRequest
 */
public class V1AffiliatesDealsPostRequestTest {
    private final V1AffiliatesDealsPostRequest model = new V1AffiliatesDealsPostRequest();

    /**
     * Model tests for V1AffiliatesDealsPostRequest
     */
    @Test
    public void testV1AffiliatesDealsPostRequest() {
        // TODO: test V1AffiliatesDealsPostRequest
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'excludedOperatorIds'
     */
    @Test
    public void excludedOperatorIdsTest() {
        // TODO: test excludedOperatorIds
    }

    /**
     * Test the property 'hideOffersLinks'
     */
    @Test
    public void hideOffersLinksTest() {
        // TODO: test hideOffersLinks
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'offerCampaign'
     */
    @Test
    public void offerCampaignTest() {
        // TODO: test offerCampaign
    }

    /**
     * Test the property 'offerType'
     */
    @Test
    public void offerTypeTest() {
        // TODO: test offerType
    }

    /**
     * Test the property 'operatorIds'
     */
    @Test
    public void operatorIdsTest() {
        // TODO: test operatorIds
    }

    /**
     * Test the property 'operatorKeys'
     */
    @Test
    public void operatorKeysTest() {
        // TODO: test operatorKeys
    }

    /**
     * Test the property 'operatorTypeIds'
     */
    @Test
    public void operatorTypeIdsTest() {
        // TODO: test operatorTypeIds
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'subnationalRegionCode'
     */
    @Test
    public void subnationalRegionCodeTest() {
        // TODO: test subnationalRegionCode
    }

    /**
     * Test the property 'withReviews'
     */
    @Test
    public void withReviewsTest() {
        // TODO: test withReviews
    }

}
