/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1AffiliatesLinksBulkPatchRequest
 */
public class V1AffiliatesLinksBulkPatchRequestTest {
    private final V1AffiliatesLinksBulkPatchRequest model = new V1AffiliatesLinksBulkPatchRequest();

    /**
     * Model tests for V1AffiliatesLinksBulkPatchRequest
     */
    @Test
    public void testV1AffiliatesLinksBulkPatchRequest() {
        // TODO: test V1AffiliatesLinksBulkPatchRequest
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'patch'
     */
    @Test
    public void patchTest() {
        // TODO: test patch
    }

}
