/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1AffiliatesEventsPostRequest
 */
public class V1AffiliatesEventsPostRequestTest {
    private final V1AffiliatesEventsPostRequest model = new V1AffiliatesEventsPostRequest();

    /**
     * Model tests for V1AffiliatesEventsPostRequest
     */
    @Test
    public void testV1AffiliatesEventsPostRequest() {
        // TODO: test V1AffiliatesEventsPostRequest
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'deviceType'
     */
    @Test
    public void deviceTypeTest() {
        // TODO: test deviceType
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'offerCampaign'
     */
    @Test
    public void offerCampaignTest() {
        // TODO: test offerCampaign
    }

    /**
     * Test the property 'offerId'
     */
    @Test
    public void offerIdTest() {
        // TODO: test offerId
    }

    /**
     * Test the property 'offerLabel'
     */
    @Test
    public void offerLabelTest() {
        // TODO: test offerLabel
    }

    /**
     * Test the property 'operatorId'
     */
    @Test
    public void operatorIdTest() {
        // TODO: test operatorId
    }

    /**
     * Test the property 'sessionToken'
     */
    @Test
    public void sessionTokenTest() {
        // TODO: test sessionToken
    }

    /**
     * Test the property 'subnationalRegionCode'
     */
    @Test
    public void subnationalRegionCodeTest() {
        // TODO: test subnationalRegionCode
    }

}
