/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1ReferencesTagTypesTagTypeIdChildrenGet200Response
 */
public class V1ReferencesTagTypesTagTypeIdChildrenGet200ResponseTest {
    private final V1ReferencesTagTypesTagTypeIdChildrenGet200Response model = new V1ReferencesTagTypesTagTypeIdChildrenGet200Response();

    /**
     * Model tests for V1ReferencesTagTypesTagTypeIdChildrenGet200Response
     */
    @Test
    public void testV1ReferencesTagTypesTagTypeIdChildrenGet200Response() {
        // TODO: test V1ReferencesTagTypesTagTypeIdChildrenGet200Response
    }

    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }

    /**
     * Test the property 'records'
     */
    @Test
    public void recordsTest() {
        // TODO: test records
    }

}
