/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1TrendsFlowsPostRequest
 */
public class V1TrendsFlowsPostRequestTest {
    private final V1TrendsFlowsPostRequest model = new V1TrendsFlowsPostRequest();

    /**
     * Model tests for V1TrendsFlowsPostRequest
     */
    @Test
    public void testV1TrendsFlowsPostRequest() {
        // TODO: test V1TrendsFlowsPostRequest
    }

    /**
     * Test the property 'betType'
     */
    @Test
    public void betTypeTest() {
        // TODO: test betType
    }

    /**
     * Test the property 'bettingMarketCategoryId'
     */
    @Test
    public void bettingMarketCategoryIdTest() {
        // TODO: test bettingMarketCategoryId
    }

    /**
     * Test the property 'bettingMarketCategoryIds'
     */
    @Test
    public void bettingMarketCategoryIdsTest() {
        // TODO: test bettingMarketCategoryIds
    }

    /**
     * Test the property 'bettingMarketEntityType'
     */
    @Test
    public void bettingMarketEntityTypeTest() {
        // TODO: test bettingMarketEntityType
    }

    /**
     * Test the property 'bettingMarketIds'
     */
    @Test
    public void bettingMarketIdsTest() {
        // TODO: test bettingMarketIds
    }

    /**
     * Test the property 'bettingMarketPositionId'
     */
    @Test
    public void bettingMarketPositionIdTest() {
        // TODO: test bettingMarketPositionId
    }

    /**
     * Test the property 'bettingMarketPositionIds'
     */
    @Test
    public void bettingMarketPositionIdsTest() {
        // TODO: test bettingMarketPositionIds
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'eventIds'
     */
    @Test
    public void eventIdsTest() {
        // TODO: test eventIds
    }

    /**
     * Test the property 'eventStartDateFrom'
     */
    @Test
    public void eventStartDateFromTest() {
        // TODO: test eventStartDateFrom
    }

    /**
     * Test the property 'eventStartDateTo'
     */
    @Test
    public void eventStartDateToTest() {
        // TODO: test eventStartDateTo
    }

    /**
     * Test the property 'factFlowType'
     */
    @Test
    public void factFlowTypeTest() {
        // TODO: test factFlowType
    }

    /**
     * Test the property 'flowType'
     */
    @Test
    public void flowTypeTest() {
        // TODO: test flowType
    }

    /**
     * Test the property 'focusEntityTypeId'
     */
    @Test
    public void focusEntityTypeIdTest() {
        // TODO: test focusEntityTypeId
    }

    /**
     * Test the property 'fullHitRate'
     */
    @Test
    public void fullHitRateTest() {
        // TODO: test fullHitRate
    }

    /**
     * Test the property 'includeAltLines'
     */
    @Test
    public void includeAltLinesTest() {
        // TODO: test includeAltLines
    }

    /**
     * Test the property 'includeDeeplinks'
     */
    @Test
    public void includeDeeplinksTest() {
        // TODO: test includeDeeplinks
    }

    /**
     * Test the property 'includeOnlyBasicTrends'
     */
    @Test
    public void includeOnlyBasicTrendsTest() {
        // TODO: test includeOnlyBasicTrends
    }

    /**
     * Test the property 'includeStarSignContent'
     */
    @Test
    public void includeStarSignContentTest() {
        // TODO: test includeStarSignContent
    }

    /**
     * Test the property 'leagueId'
     */
    @Test
    public void leagueIdTest() {
        // TODO: test leagueId
    }

    /**
     * Test the property 'leagueIds'
     */
    @Test
    public void leagueIdsTest() {
        // TODO: test leagueIds
    }

    /**
     * Test the property 'leagueKey'
     */
    @Test
    public void leagueKeyTest() {
        // TODO: test leagueKey
    }

    /**
     * Test the property 'likelihoodType'
     */
    @Test
    public void likelihoodTypeTest() {
        // TODO: test likelihoodType
    }

    /**
     * Test the property 'maxHitRateThreshold'
     */
    @Test
    public void maxHitRateThresholdTest() {
        // TODO: test maxHitRateThreshold
    }

    /**
     * Test the property 'maxImpliedProbabilityThreshold'
     */
    @Test
    public void maxImpliedProbabilityThresholdTest() {
        // TODO: test maxImpliedProbabilityThreshold
    }

    /**
     * Test the property 'minHitRateThreshold'
     */
    @Test
    public void minHitRateThresholdTest() {
        // TODO: test minHitRateThreshold
    }

    /**
     * Test the property 'minImpliedProbabilityThreshold'
     */
    @Test
    public void minImpliedProbabilityThresholdTest() {
        // TODO: test minImpliedProbabilityThreshold
    }

    /**
     * Test the property 'oddsFormat'
     */
    @Test
    public void oddsFormatTest() {
        // TODO: test oddsFormat
    }

    /**
     * Test the property 'operatorIds'
     */
    @Test
    public void operatorIdsTest() {
        // TODO: test operatorIds
    }

    /**
     * Test the property 'operatorKeys'
     */
    @Test
    public void operatorKeysTest() {
        // TODO: test operatorKeys
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'playerId'
     */
    @Test
    public void playerIdTest() {
        // TODO: test playerId
    }

    /**
     * Test the property 'playerIds'
     */
    @Test
    public void playerIdsTest() {
        // TODO: test playerIds
    }

    /**
     * Test the property 'playerKey'
     */
    @Test
    public void playerKeyTest() {
        // TODO: test playerKey
    }

    /**
     * Test the property 'productMode'
     */
    @Test
    public void productModeTest() {
        // TODO: test productMode
    }

    /**
     * Test the property 'splitType'
     */
    @Test
    public void splitTypeTest() {
        // TODO: test splitType
    }

    /**
     * Test the property 'sportId'
     */
    @Test
    public void sportIdTest() {
        // TODO: test sportId
    }

    /**
     * Test the property 'sportIds'
     */
    @Test
    public void sportIdsTest() {
        // TODO: test sportIds
    }

    /**
     * Test the property 'sportKey'
     */
    @Test
    public void sportKeyTest() {
        // TODO: test sportKey
    }

    /**
     * Test the property 'startingSoon'
     */
    @Test
    public void startingSoonTest() {
        // TODO: test startingSoon
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'teamIds'
     */
    @Test
    public void teamIdsTest() {
        // TODO: test teamIds
    }

    /**
     * Test the property 'teamKey'
     */
    @Test
    public void teamKeyTest() {
        // TODO: test teamKey
    }

    /**
     * Test the property 'teamSplit'
     */
    @Test
    public void teamSplitTest() {
        // TODO: test teamSplit
    }

    /**
     * Test the property 'useCartoonImages'
     */
    @Test
    public void useCartoonImagesTest() {
        // TODO: test useCartoonImages
    }

}
