/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1TrendsFlowsByIdPostRequest
 */
public class V1TrendsFlowsByIdPostRequestTest {
    private final V1TrendsFlowsByIdPostRequest model = new V1TrendsFlowsByIdPostRequest();

    /**
     * Model tests for V1TrendsFlowsByIdPostRequest
     */
    @Test
    public void testV1TrendsFlowsByIdPostRequest() {
        // TODO: test V1TrendsFlowsByIdPostRequest
    }

    /**
     * Test the property 'factFlowType'
     */
    @Test
    public void factFlowTypeTest() {
        // TODO: test factFlowType
    }

    /**
     * Test the property 'flowIds'
     */
    @Test
    public void flowIdsTest() {
        // TODO: test flowIds
    }

    /**
     * Test the property 'flowType'
     */
    @Test
    public void flowTypeTest() {
        // TODO: test flowType
    }

    /**
     * Test the property 'useCartoonImages'
     */
    @Test
    public void useCartoonImagesTest() {
        // TODO: test useCartoonImages
    }

}
