/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * AuthSetCheckEndpointRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class AuthSetCheckEndpointRequest {
  public static final String SERIALIZED_NAME_ALLOW_MULTIPLE = "allow_multiple";
  @SerializedName(SERIALIZED_NAME_ALLOW_MULTIPLE)
  @javax.annotation.Nullable
  private Boolean allowMultiple = false;

  public static final String SERIALIZED_NAME_AUTH_HEADER_NAME = "auth_header_name";
  @SerializedName(SERIALIZED_NAME_AUTH_HEADER_NAME)
  @javax.annotation.Nullable
  private String authHeaderName;

  public static final String SERIALIZED_NAME_AUTH_SCHEME = "auth_scheme";
  @SerializedName(SERIALIZED_NAME_AUTH_SCHEME)
  @javax.annotation.Nullable
  private String authScheme;

  public static final String SERIALIZED_NAME_AUTH_TOKEN = "auth_token";
  @SerializedName(SERIALIZED_NAME_AUTH_TOKEN)
  @javax.annotation.Nonnull
  private String authToken;

  /**
   * HTTP method used when calling the endpoint.
   */
  @JsonAdapter(MethodEnum.Adapter.class)
  public enum MethodEnum {
    POST("POST");

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MethodEnum fromValue(String value) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  @javax.annotation.Nonnull
  private MethodEnum method;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private URI url;

  public AuthSetCheckEndpointRequest() {
  }

  public AuthSetCheckEndpointRequest allowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
    return this;
  }

  /**
   * If true, the platform sends a single POST with a JSON array of all hydrated payloads. If false (default), one POST per flow is issued in parallel.
   * @return allowMultiple
   */
  @javax.annotation.Nullable
  public Boolean getAllowMultiple() {
    return allowMultiple;
  }

  public void setAllowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
  }


  public AuthSetCheckEndpointRequest authHeaderName(@javax.annotation.Nullable String authHeaderName) {
    this.authHeaderName = authHeaderName;
    return this;
  }

  /**
   * HTTP header name used to carry the authentication credential. Defaults to &#39;Authorization&#39;. Common alternatives: &#39;X-API-Key&#39;, &#39;X-Auth&#39;.
   * @return authHeaderName
   */
  @javax.annotation.Nullable
  public String getAuthHeaderName() {
    return authHeaderName;
  }

  public void setAuthHeaderName(@javax.annotation.Nullable String authHeaderName) {
    this.authHeaderName = authHeaderName;
  }


  public AuthSetCheckEndpointRequest authScheme(@javax.annotation.Nullable String authScheme) {
    this.authScheme = authScheme;
    return this;
  }

  /**
   * Prefix placed before the token in the header value. Defaults to &#39;Bearer&#39; when &#39;auth_header_name&#39; is omitted. Set to an empty string for headers that take the raw value (e.g. &#39;X-API-Key&#39;).
   * @return authScheme
   */
  @javax.annotation.Nullable
  public String getAuthScheme() {
    return authScheme;
  }

  public void setAuthScheme(@javax.annotation.Nullable String authScheme) {
    this.authScheme = authScheme;
  }


  public AuthSetCheckEndpointRequest authToken(@javax.annotation.Nonnull String authToken) {
    this.authToken = authToken;
    return this;
  }

  /**
   * Authentication credential. Stored server-side and never returned in any response. Sent as &#x60;&lt;auth_header_name&gt;: &lt;auth_scheme&gt; &lt;auth_token&gt;&#x60; (scheme omitted when empty).
   * @return authToken
   */
  @javax.annotation.Nonnull
  public String getAuthToken() {
    return authToken;
  }

  public void setAuthToken(@javax.annotation.Nonnull String authToken) {
    this.authToken = authToken;
  }


  public AuthSetCheckEndpointRequest method(@javax.annotation.Nonnull MethodEnum method) {
    this.method = method;
    return this;
  }

  /**
   * HTTP method used when calling the endpoint.
   * @return method
   */
  @javax.annotation.Nonnull
  public MethodEnum getMethod() {
    return method;
  }

  public void setMethod(@javax.annotation.Nonnull MethodEnum method) {
    this.method = method;
  }


  public AuthSetCheckEndpointRequest url(@javax.annotation.Nonnull URI url) {
    this.url = url;
    return this;
  }

  /**
   * Absolute URL of the check endpoint (https recommended).
   * @return url
   */
  @javax.annotation.Nonnull
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull URI url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthSetCheckEndpointRequest authSetCheckEndpointRequest = (AuthSetCheckEndpointRequest) o;
    return Objects.equals(this.allowMultiple, authSetCheckEndpointRequest.allowMultiple) &&
        Objects.equals(this.authHeaderName, authSetCheckEndpointRequest.authHeaderName) &&
        Objects.equals(this.authScheme, authSetCheckEndpointRequest.authScheme) &&
        Objects.equals(this.authToken, authSetCheckEndpointRequest.authToken) &&
        Objects.equals(this.method, authSetCheckEndpointRequest.method) &&
        Objects.equals(this.url, authSetCheckEndpointRequest.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMultiple, authHeaderName, authScheme, authToken, method, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthSetCheckEndpointRequest {\n");
    sb.append("    allowMultiple: ").append(toIndentedString(allowMultiple)).append("\n");
    sb.append("    authHeaderName: ").append(toIndentedString(authHeaderName)).append("\n");
    sb.append("    authScheme: ").append(toIndentedString(authScheme)).append("\n");
    sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("allow_multiple", "auth_header_name", "auth_scheme", "auth_token", "method", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("auth_token", "method", "url"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuthSetCheckEndpointRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthSetCheckEndpointRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuthSetCheckEndpointRequest is not found in the empty JSON string", AuthSetCheckEndpointRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuthSetCheckEndpointRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuthSetCheckEndpointRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AuthSetCheckEndpointRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("auth_header_name") != null && !jsonObj.get("auth_header_name").isJsonNull()) && !jsonObj.get("auth_header_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_header_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_header_name").toString()));
      }
      if ((jsonObj.get("auth_scheme") != null && !jsonObj.get("auth_scheme").isJsonNull()) && !jsonObj.get("auth_scheme").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_scheme` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_scheme").toString()));
      }
      if (!jsonObj.get("auth_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_token").toString()));
      }
      if (!jsonObj.get("method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method").toString()));
      }
      // validate the required field `method`
      MethodEnum.validateJsonElement(jsonObj.get("method"));
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthSetCheckEndpointRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthSetCheckEndpointRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthSetCheckEndpointRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthSetCheckEndpointRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthSetCheckEndpointRequest>() {
           @Override
           public void write(JsonWriter out, AuthSetCheckEndpointRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthSetCheckEndpointRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuthSetCheckEndpointRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuthSetCheckEndpointRequest
   * @throws IOException if the JSON string is invalid with respect to AuthSetCheckEndpointRequest
   */
  public static AuthSetCheckEndpointRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthSetCheckEndpointRequest.class);
  }

  /**
   * Convert an instance of AuthSetCheckEndpointRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

