/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * AuthCheckEndpointResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class AuthCheckEndpointResponseData {
  public static final String SERIALIZED_NAME_ALLOW_MULTIPLE = "allow_multiple";
  @SerializedName(SERIALIZED_NAME_ALLOW_MULTIPLE)
  @javax.annotation.Nullable
  private Boolean allowMultiple;

  public static final String SERIALIZED_NAME_AUTH_HEADER_NAME = "auth_header_name";
  @SerializedName(SERIALIZED_NAME_AUTH_HEADER_NAME)
  @javax.annotation.Nullable
  private String authHeaderName;

  public static final String SERIALIZED_NAME_AUTH_SCHEME = "auth_scheme";
  @SerializedName(SERIALIZED_NAME_AUTH_SCHEME)
  @javax.annotation.Nullable
  private String authScheme;

  public static final String SERIALIZED_NAME_AUTH_TOKEN_PREVIEW = "auth_token_preview";
  @SerializedName(SERIALIZED_NAME_AUTH_TOKEN_PREVIEW)
  @javax.annotation.Nullable
  private String authTokenPreview;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  /**
   * Gets or Sets method
   */
  @JsonAdapter(MethodEnum.Adapter.class)
  public enum MethodEnum {
    POST("POST");

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MethodEnum fromValue(String value) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  @javax.annotation.Nullable
  private MethodEnum method;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private URI url;

  public AuthCheckEndpointResponseData() {
  }

  public AuthCheckEndpointResponseData allowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
    return this;
  }

  /**
   * Get allowMultiple
   * @return allowMultiple
   */
  @javax.annotation.Nullable
  public Boolean getAllowMultiple() {
    return allowMultiple;
  }

  public void setAllowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
  }


  public AuthCheckEndpointResponseData authHeaderName(@javax.annotation.Nullable String authHeaderName) {
    this.authHeaderName = authHeaderName;
    return this;
  }

  /**
   * Get authHeaderName
   * @return authHeaderName
   */
  @javax.annotation.Nullable
  public String getAuthHeaderName() {
    return authHeaderName;
  }

  public void setAuthHeaderName(@javax.annotation.Nullable String authHeaderName) {
    this.authHeaderName = authHeaderName;
  }


  public AuthCheckEndpointResponseData authScheme(@javax.annotation.Nullable String authScheme) {
    this.authScheme = authScheme;
    return this;
  }

  /**
   * May be empty for raw-value header schemes like &#39;X-API-Key&#39;.
   * @return authScheme
   */
  @javax.annotation.Nullable
  public String getAuthScheme() {
    return authScheme;
  }

  public void setAuthScheme(@javax.annotation.Nullable String authScheme) {
    this.authScheme = authScheme;
  }


  public AuthCheckEndpointResponseData authTokenPreview(@javax.annotation.Nullable String authTokenPreview) {
    this.authTokenPreview = authTokenPreview;
    return this;
  }

  /**
   * Masked preview of the stored auth token (e.g. \&quot;…aB3x\&quot;). The full token is never returned.
   * @return authTokenPreview
   */
  @javax.annotation.Nullable
  public String getAuthTokenPreview() {
    return authTokenPreview;
  }

  public void setAuthTokenPreview(@javax.annotation.Nullable String authTokenPreview) {
    this.authTokenPreview = authTokenPreview;
  }


  public AuthCheckEndpointResponseData createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AuthCheckEndpointResponseData method(@javax.annotation.Nullable MethodEnum method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  public MethodEnum getMethod() {
    return method;
  }

  public void setMethod(@javax.annotation.Nullable MethodEnum method) {
    this.method = method;
  }


  public AuthCheckEndpointResponseData updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public AuthCheckEndpointResponseData url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthCheckEndpointResponseData authCheckEndpointResponseData = (AuthCheckEndpointResponseData) o;
    return Objects.equals(this.allowMultiple, authCheckEndpointResponseData.allowMultiple) &&
        Objects.equals(this.authHeaderName, authCheckEndpointResponseData.authHeaderName) &&
        Objects.equals(this.authScheme, authCheckEndpointResponseData.authScheme) &&
        Objects.equals(this.authTokenPreview, authCheckEndpointResponseData.authTokenPreview) &&
        Objects.equals(this.createdAt, authCheckEndpointResponseData.createdAt) &&
        Objects.equals(this.method, authCheckEndpointResponseData.method) &&
        Objects.equals(this.updatedAt, authCheckEndpointResponseData.updatedAt) &&
        Objects.equals(this.url, authCheckEndpointResponseData.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMultiple, authHeaderName, authScheme, authTokenPreview, createdAt, method, updatedAt, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthCheckEndpointResponseData {\n");
    sb.append("    allowMultiple: ").append(toIndentedString(allowMultiple)).append("\n");
    sb.append("    authHeaderName: ").append(toIndentedString(authHeaderName)).append("\n");
    sb.append("    authScheme: ").append(toIndentedString(authScheme)).append("\n");
    sb.append("    authTokenPreview: ").append(toIndentedString(authTokenPreview)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("allow_multiple", "auth_header_name", "auth_scheme", "auth_token_preview", "created_at", "method", "updated_at", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuthCheckEndpointResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthCheckEndpointResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuthCheckEndpointResponseData is not found in the empty JSON string", AuthCheckEndpointResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuthCheckEndpointResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuthCheckEndpointResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("auth_header_name") != null && !jsonObj.get("auth_header_name").isJsonNull()) && !jsonObj.get("auth_header_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_header_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_header_name").toString()));
      }
      if ((jsonObj.get("auth_scheme") != null && !jsonObj.get("auth_scheme").isJsonNull()) && !jsonObj.get("auth_scheme").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_scheme` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_scheme").toString()));
      }
      if ((jsonObj.get("auth_token_preview") != null && !jsonObj.get("auth_token_preview").isJsonNull()) && !jsonObj.get("auth_token_preview").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_token_preview` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_token_preview").toString()));
      }
      if ((jsonObj.get("method") != null && !jsonObj.get("method").isJsonNull()) && !jsonObj.get("method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method").toString()));
      }
      // validate the optional field `method`
      if (jsonObj.get("method") != null && !jsonObj.get("method").isJsonNull()) {
        MethodEnum.validateJsonElement(jsonObj.get("method"));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthCheckEndpointResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthCheckEndpointResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthCheckEndpointResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthCheckEndpointResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthCheckEndpointResponseData>() {
           @Override
           public void write(JsonWriter out, AuthCheckEndpointResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthCheckEndpointResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuthCheckEndpointResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuthCheckEndpointResponseData
   * @throws IOException if the JSON string is invalid with respect to AuthCheckEndpointResponseData
   */
  public static AuthCheckEndpointResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthCheckEndpointResponseData.class);
  }

  /**
   * Convert an instance of AuthCheckEndpointResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

