/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * AuthListAPIKeysResponseApiKeysInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class AuthListAPIKeysResponseApiKeysInner {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Boolean active;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_KEY_CODE = "key_code";
  @SerializedName(SERIALIZED_NAME_KEY_CODE)
  @javax.annotation.Nullable
  private UUID keyCode;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_WIDGET = "widget";
  @SerializedName(SERIALIZED_NAME_WIDGET)
  @javax.annotation.Nullable
  private Boolean widget;

  public AuthListAPIKeysResponseApiKeysInner() {
  }

  public AuthListAPIKeysResponseApiKeysInner active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   */
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public AuthListAPIKeysResponseApiKeysInner createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AuthListAPIKeysResponseApiKeysInner expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public AuthListAPIKeysResponseApiKeysInner keyCode(@javax.annotation.Nullable UUID keyCode) {
    this.keyCode = keyCode;
    return this;
  }

  /**
   * Get keyCode
   * @return keyCode
   */
  @javax.annotation.Nullable
  public UUID getKeyCode() {
    return keyCode;
  }

  public void setKeyCode(@javax.annotation.Nullable UUID keyCode) {
    this.keyCode = keyCode;
  }


  public AuthListAPIKeysResponseApiKeysInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AuthListAPIKeysResponseApiKeysInner widget(@javax.annotation.Nullable Boolean widget) {
    this.widget = widget;
    return this;
  }

  /**
   * Get widget
   * @return widget
   */
  @javax.annotation.Nullable
  public Boolean getWidget() {
    return widget;
  }

  public void setWidget(@javax.annotation.Nullable Boolean widget) {
    this.widget = widget;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthListAPIKeysResponseApiKeysInner authListAPIKeysResponseApiKeysInner = (AuthListAPIKeysResponseApiKeysInner) o;
    return Objects.equals(this.active, authListAPIKeysResponseApiKeysInner.active) &&
        Objects.equals(this.createdAt, authListAPIKeysResponseApiKeysInner.createdAt) &&
        Objects.equals(this.expiresAt, authListAPIKeysResponseApiKeysInner.expiresAt) &&
        Objects.equals(this.keyCode, authListAPIKeysResponseApiKeysInner.keyCode) &&
        Objects.equals(this.name, authListAPIKeysResponseApiKeysInner.name) &&
        Objects.equals(this.widget, authListAPIKeysResponseApiKeysInner.widget);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, createdAt, expiresAt, keyCode, name, widget);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthListAPIKeysResponseApiKeysInner {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    keyCode: ").append(toIndentedString(keyCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    widget: ").append(toIndentedString(widget)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("active", "created_at", "expires_at", "key_code", "name", "widget"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuthListAPIKeysResponseApiKeysInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthListAPIKeysResponseApiKeysInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuthListAPIKeysResponseApiKeysInner is not found in the empty JSON string", AuthListAPIKeysResponseApiKeysInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuthListAPIKeysResponseApiKeysInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuthListAPIKeysResponseApiKeysInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("key_code") != null && !jsonObj.get("key_code").isJsonNull()) && !jsonObj.get("key_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key_code").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthListAPIKeysResponseApiKeysInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthListAPIKeysResponseApiKeysInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthListAPIKeysResponseApiKeysInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthListAPIKeysResponseApiKeysInner.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthListAPIKeysResponseApiKeysInner>() {
           @Override
           public void write(JsonWriter out, AuthListAPIKeysResponseApiKeysInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthListAPIKeysResponseApiKeysInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuthListAPIKeysResponseApiKeysInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuthListAPIKeysResponseApiKeysInner
   * @throws IOException if the JSON string is invalid with respect to AuthListAPIKeysResponseApiKeysInner
   */
  public static AuthListAPIKeysResponseApiKeysInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthListAPIKeysResponseApiKeysInner.class);
  }

  /**
   * Convert an instance of AuthListAPIKeysResponseApiKeysInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

