/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * AuthListSecretsResponseSecretsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class AuthListSecretsResponseSecretsInner {
  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_SECRET_CODE = "secret_code";
  @SerializedName(SERIALIZED_NAME_SECRET_CODE)
  @javax.annotation.Nullable
  private UUID secretCode;

  public static final String SERIALIZED_NAME_SECRET_PREVIEW = "secret_preview";
  @SerializedName(SERIALIZED_NAME_SECRET_PREVIEW)
  @javax.annotation.Nullable
  private String secretPreview;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public AuthListSecretsResponseSecretsInner() {
  }

  public AuthListSecretsResponseSecretsInner createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AuthListSecretsResponseSecretsInner secretCode(@javax.annotation.Nullable UUID secretCode) {
    this.secretCode = secretCode;
    return this;
  }

  /**
   * Get secretCode
   * @return secretCode
   */
  @javax.annotation.Nullable
  public UUID getSecretCode() {
    return secretCode;
  }

  public void setSecretCode(@javax.annotation.Nullable UUID secretCode) {
    this.secretCode = secretCode;
  }


  public AuthListSecretsResponseSecretsInner secretPreview(@javax.annotation.Nullable String secretPreview) {
    this.secretPreview = secretPreview;
    return this;
  }

  /**
   * Masked secret preview (e.g. betflow_b2b_...5678901234)
   * @return secretPreview
   */
  @javax.annotation.Nullable
  public String getSecretPreview() {
    return secretPreview;
  }

  public void setSecretPreview(@javax.annotation.Nullable String secretPreview) {
    this.secretPreview = secretPreview;
  }


  public AuthListSecretsResponseSecretsInner updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthListSecretsResponseSecretsInner authListSecretsResponseSecretsInner = (AuthListSecretsResponseSecretsInner) o;
    return Objects.equals(this.createdAt, authListSecretsResponseSecretsInner.createdAt) &&
        Objects.equals(this.secretCode, authListSecretsResponseSecretsInner.secretCode) &&
        Objects.equals(this.secretPreview, authListSecretsResponseSecretsInner.secretPreview) &&
        Objects.equals(this.updatedAt, authListSecretsResponseSecretsInner.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, secretCode, secretPreview, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthListSecretsResponseSecretsInner {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    secretCode: ").append(toIndentedString(secretCode)).append("\n");
    sb.append("    secretPreview: ").append(toIndentedString(secretPreview)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("created_at", "secret_code", "secret_preview", "updated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuthListSecretsResponseSecretsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthListSecretsResponseSecretsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuthListSecretsResponseSecretsInner is not found in the empty JSON string", AuthListSecretsResponseSecretsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AuthListSecretsResponseSecretsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AuthListSecretsResponseSecretsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("secret_code") != null && !jsonObj.get("secret_code").isJsonNull()) && !jsonObj.get("secret_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `secret_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secret_code").toString()));
      }
      if ((jsonObj.get("secret_preview") != null && !jsonObj.get("secret_preview").isJsonNull()) && !jsonObj.get("secret_preview").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `secret_preview` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secret_preview").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthListSecretsResponseSecretsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthListSecretsResponseSecretsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthListSecretsResponseSecretsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthListSecretsResponseSecretsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthListSecretsResponseSecretsInner>() {
           @Override
           public void write(JsonWriter out, AuthListSecretsResponseSecretsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthListSecretsResponseSecretsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuthListSecretsResponseSecretsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuthListSecretsResponseSecretsInner
   * @throws IOException if the JSON string is invalid with respect to AuthListSecretsResponseSecretsInner
   */
  public static AuthListSecretsResponseSecretsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthListSecretsResponseSecretsInner.class);
  }

  /**
   * Convert an instance of AuthListSecretsResponseSecretsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

