/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * TrendsErrorResponseError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TrendsErrorResponseError {
  /**
   * Machine-readable error code. Possible values:   * &#x60;BAD_REQUEST&#x60; — malformed request, invalid path/query parameter, or JSON type mismatch in the body. Returned with HTTP 400.   * &#x60;VALIDATION_ERROR&#x60; — one or more request fields failed validation rules; the message names each offending field. Returned with HTTP 422 (Unprocessable Entity).   * &#x60;AMBIGUOUS_LOOKUP&#x60; — a slug identifier matched more than one record; qualify it (e.g. &#x60;country/league&#x60;) and retry.   * &#x60;UNAUTHORIZED&#x60; — missing or invalid credentials.   * &#x60;FORBIDDEN&#x60; — authenticated but not permitted to access this resource.   * &#x60;NOT_FOUND&#x60; — resource does not exist.   * &#x60;RATE_LIMIT_EXCEEDED&#x60; — too many requests.   * &#x60;INTERNAL_ERROR&#x60; — unexpected server error. 
   */
  @JsonAdapter(CodeEnum.Adapter.class)
  public enum CodeEnum {
    BAD_REQUEST("BAD_REQUEST"),
    
    VALIDATION_ERROR("VALIDATION_ERROR"),
    
    AMBIGUOUS_LOOKUP("AMBIGUOUS_LOOKUP"),
    
    UNAUTHORIZED("UNAUTHORIZED"),
    
    FORBIDDEN("FORBIDDEN"),
    
    NOT_FOUND("NOT_FOUND"),
    
    RATE_LIMIT_EXCEEDED("RATE_LIMIT_EXCEEDED"),
    
    INTERNAL_ERROR("INTERNAL_ERROR");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CodeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CodeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nonnull
  private CodeEnum code;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nonnull
  private String message;

  public TrendsErrorResponseError() {
  }

  public TrendsErrorResponseError code(@javax.annotation.Nonnull CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Machine-readable error code. Possible values:   * &#x60;BAD_REQUEST&#x60; — malformed request, invalid path/query parameter, or JSON type mismatch in the body. Returned with HTTP 400.   * &#x60;VALIDATION_ERROR&#x60; — one or more request fields failed validation rules; the message names each offending field. Returned with HTTP 422 (Unprocessable Entity).   * &#x60;AMBIGUOUS_LOOKUP&#x60; — a slug identifier matched more than one record; qualify it (e.g. &#x60;country/league&#x60;) and retry.   * &#x60;UNAUTHORIZED&#x60; — missing or invalid credentials.   * &#x60;FORBIDDEN&#x60; — authenticated but not permitted to access this resource.   * &#x60;NOT_FOUND&#x60; — resource does not exist.   * &#x60;RATE_LIMIT_EXCEEDED&#x60; — too many requests.   * &#x60;INTERNAL_ERROR&#x60; — unexpected server error. 
   * @return code
   */
  @javax.annotation.Nonnull
  public CodeEnum getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nonnull CodeEnum code) {
    this.code = code;
  }


  public TrendsErrorResponseError message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Human-readable explanation of the error. For &#x60;VALIDATION_ERROR&#x60; responses, names the offending field(s) and the rule that failed.
   * @return message
   */
  @javax.annotation.Nonnull
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrendsErrorResponseError trendsErrorResponseError = (TrendsErrorResponseError) o;
    return Objects.equals(this.code, trendsErrorResponseError.code) &&
        Objects.equals(this.message, trendsErrorResponseError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrendsErrorResponseError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "message"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("code", "message"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TrendsErrorResponseError
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TrendsErrorResponseError.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TrendsErrorResponseError is not found in the empty JSON string", TrendsErrorResponseError.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TrendsErrorResponseError.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TrendsErrorResponseError` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TrendsErrorResponseError.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      // validate the required field `code`
      CodeEnum.validateJsonElement(jsonObj.get("code"));
      if (!jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrendsErrorResponseError.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrendsErrorResponseError' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrendsErrorResponseError> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrendsErrorResponseError.class));

       return (TypeAdapter<T>) new TypeAdapter<TrendsErrorResponseError>() {
           @Override
           public void write(JsonWriter out, TrendsErrorResponseError value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TrendsErrorResponseError read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TrendsErrorResponseError given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TrendsErrorResponseError
   * @throws IOException if the JSON string is invalid with respect to TrendsErrorResponseError
   */
  public static TrendsErrorResponseError fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrendsErrorResponseError.class);
  }

  /**
   * Convert an instance of TrendsErrorResponseError to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

