/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TrendsQuoteSandboxRequest {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nonnull
  private String country;

  public static final String SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_MAPS = "event_betting_market_position_maps";
  @SerializedName(SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_MAPS)
  @javax.annotation.Nonnull
  private List<Object> eventBettingMarketPositionMaps = new ArrayList<>();

  public static final String SERIALIZED_NAME_FLOW_ID = "flow_id";
  @SerializedName(SERIALIZED_NAME_FLOW_ID)
  @javax.annotation.Nonnull
  private Long flowId;

  /**
   * Gets or Sets flowType
   */
  @JsonAdapter(FlowTypeEnum.Adapter.class)
  public enum FlowTypeEnum {
    FACT_FLOW("fact_flow"),
    
    FUN_FLOW("fun_flow"),
    
    FACT_FLOW_PARLAY("fact_flow_parlay"),
    
    FUN_FLOW_PARLAY("fun_flow_parlay"),
    
    PLAIN_FLOW_PARLAY("plain_flow_parlay");

    private String value;

    FlowTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FlowTypeEnum fromValue(String value) {
      for (FlowTypeEnum b : FlowTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FlowTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FlowTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FlowTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FlowTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FlowTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FLOW_TYPE = "flow_type";
  @SerializedName(SERIALIZED_NAME_FLOW_TYPE)
  @javax.annotation.Nonnull
  private FlowTypeEnum flowType;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nullable
  private String region;

  public TrendsQuoteSandboxRequest() {
  }

  public TrendsQuoteSandboxRequest country(@javax.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nonnull
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nonnull String country) {
    this.country = country;
  }


  public TrendsQuoteSandboxRequest eventBettingMarketPositionMaps(@javax.annotation.Nonnull List<Object> eventBettingMarketPositionMaps) {
    this.eventBettingMarketPositionMaps = eventBettingMarketPositionMaps;
    return this;
  }

  public TrendsQuoteSandboxRequest addEventBettingMarketPositionMapsItem(Object eventBettingMarketPositionMapsItem) {
    if (this.eventBettingMarketPositionMaps == null) {
      this.eventBettingMarketPositionMaps = new ArrayList<>();
    }
    this.eventBettingMarketPositionMaps.add(eventBettingMarketPositionMapsItem);
    return this;
  }

  /**
   * Hydrated leg array, identical to what the quote endpoint POSTs to a real operator. Pass it through unchanged.
   * @return eventBettingMarketPositionMaps
   */
  @javax.annotation.Nonnull
  public List<Object> getEventBettingMarketPositionMaps() {
    return eventBettingMarketPositionMaps;
  }

  public void setEventBettingMarketPositionMaps(@javax.annotation.Nonnull List<Object> eventBettingMarketPositionMaps) {
    this.eventBettingMarketPositionMaps = eventBettingMarketPositionMaps;
  }


  public TrendsQuoteSandboxRequest flowId(@javax.annotation.Nonnull Long flowId) {
    this.flowId = flowId;
    return this;
  }

  /**
   * Get flowId
   * @return flowId
   */
  @javax.annotation.Nonnull
  public Long getFlowId() {
    return flowId;
  }

  public void setFlowId(@javax.annotation.Nonnull Long flowId) {
    this.flowId = flowId;
  }


  public TrendsQuoteSandboxRequest flowType(@javax.annotation.Nonnull FlowTypeEnum flowType) {
    this.flowType = flowType;
    return this;
  }

  /**
   * Get flowType
   * @return flowType
   */
  @javax.annotation.Nonnull
  public FlowTypeEnum getFlowType() {
    return flowType;
  }

  public void setFlowType(@javax.annotation.Nonnull FlowTypeEnum flowType) {
    this.flowType = flowType;
  }


  public TrendsQuoteSandboxRequest region(@javax.annotation.Nullable String region) {
    this.region = region;
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @javax.annotation.Nullable
  public String getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrendsQuoteSandboxRequest trendsQuoteSandboxRequest = (TrendsQuoteSandboxRequest) o;
    return Objects.equals(this.country, trendsQuoteSandboxRequest.country) &&
        Objects.equals(this.eventBettingMarketPositionMaps, trendsQuoteSandboxRequest.eventBettingMarketPositionMaps) &&
        Objects.equals(this.flowId, trendsQuoteSandboxRequest.flowId) &&
        Objects.equals(this.flowType, trendsQuoteSandboxRequest.flowType) &&
        Objects.equals(this.region, trendsQuoteSandboxRequest.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, eventBettingMarketPositionMaps, flowId, flowType, region);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrendsQuoteSandboxRequest {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    eventBettingMarketPositionMaps: ").append(toIndentedString(eventBettingMarketPositionMaps)).append("\n");
    sb.append("    flowId: ").append(toIndentedString(flowId)).append("\n");
    sb.append("    flowType: ").append(toIndentedString(flowType)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country", "event_betting_market_position_maps", "flow_id", "flow_type", "region"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("country", "event_betting_market_position_maps", "flow_id", "flow_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TrendsQuoteSandboxRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TrendsQuoteSandboxRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TrendsQuoteSandboxRequest is not found in the empty JSON string", TrendsQuoteSandboxRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TrendsQuoteSandboxRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TrendsQuoteSandboxRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TrendsQuoteSandboxRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("event_betting_market_position_maps") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("event_betting_market_position_maps").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_betting_market_position_maps` to be an array in the JSON string but got `%s`", jsonObj.get("event_betting_market_position_maps").toString()));
      }
      if (!jsonObj.get("flow_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `flow_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flow_type").toString()));
      }
      // validate the required field `flow_type`
      FlowTypeEnum.validateJsonElement(jsonObj.get("flow_type"));
      if ((jsonObj.get("region") != null && !jsonObj.get("region").isJsonNull()) && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrendsQuoteSandboxRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrendsQuoteSandboxRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrendsQuoteSandboxRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrendsQuoteSandboxRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TrendsQuoteSandboxRequest>() {
           @Override
           public void write(JsonWriter out, TrendsQuoteSandboxRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TrendsQuoteSandboxRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TrendsQuoteSandboxRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TrendsQuoteSandboxRequest
   * @throws IOException if the JSON string is invalid with respect to TrendsQuoteSandboxRequest
   */
  public static TrendsQuoteSandboxRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrendsQuoteSandboxRequest.class);
  }

  /**
   * Convert an instance of TrendsQuoteSandboxRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

