/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * TrendsWidgetEventRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TrendsWidgetEventRequest {
  public static final String SERIALIZED_NAME_EVENT_BODY = "event_body";
  @SerializedName(SERIALIZED_NAME_EVENT_BODY)
  @javax.annotation.Nonnull
  private Map<String, Object> eventBody = new HashMap<>();

  /**
   * The kind of client-side widget interaction being reported.
   */
  @JsonAdapter(EventTypeEnum.Adapter.class)
  public enum EventTypeEnum {
    IMPRESSION("impression"),
    
    CLICK("click"),
    
    DWELL("dwell"),
    
    CART_OPEN("cart_open"),
    
    CART_OFFERS_SHOWN("cart_offers_shown"),
    
    CART_DISMISS("cart_dismiss"),
    
    CARD_CLICK("card_click"),
    
    GRAPH_EXPAND("graph_expand"),
    
    GRAPH_METRIC_CHANGE("graph_metric_change"),
    
    FILTER_CHANGE("filter_change"),
    
    WIDGET_IMPRESSION("widget-impression"),
    
    WIDGET_VIEWED("widget-viewed"),
    
    BETSLIP_CLICKED("betslip-clicked"),
    
    BETSLIP_SHARED("betslip-shared"),
    
    FLOW_CLICKED("flow-clicked"),
    
    FLOW_SHARED("flow-shared");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EventTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EventTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EventTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nonnull
  private EventTypeEnum eventType;

  /**
   * Optional widget mode the interaction occurred in. Defaults to &#x60;clean&#x60;.
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    OPERATOR("operator"),
    
    AFFILIATE("affiliate"),
    
    CLEAN("clean");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nullable
  private ModeEnum mode;

  public TrendsWidgetEventRequest() {
  }

  public TrendsWidgetEventRequest eventBody(@javax.annotation.Nonnull Map<String, Object> eventBody) {
    this.eventBody = eventBody;
    return this;
  }

  public TrendsWidgetEventRequest putEventBodyItem(String key, Object eventBodyItem) {
    if (this.eventBody == null) {
      this.eventBody = new HashMap<>();
    }
    this.eventBody.put(key, eventBodyItem);
    return this;
  }

  /**
   * Arbitrary JSON object carrying event-specific fields. May be an empty object.
   * @return eventBody
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getEventBody() {
    return eventBody;
  }

  public void setEventBody(@javax.annotation.Nonnull Map<String, Object> eventBody) {
    this.eventBody = eventBody;
  }


  public TrendsWidgetEventRequest eventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * The kind of client-side widget interaction being reported.
   * @return eventType
   */
  @javax.annotation.Nonnull
  public EventTypeEnum getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public TrendsWidgetEventRequest mode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Optional widget mode the interaction occurred in. Defaults to &#x60;clean&#x60;.
   * @return mode
   */
  @javax.annotation.Nullable
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrendsWidgetEventRequest trendsWidgetEventRequest = (TrendsWidgetEventRequest) o;
    return Objects.equals(this.eventBody, trendsWidgetEventRequest.eventBody) &&
        Objects.equals(this.eventType, trendsWidgetEventRequest.eventType) &&
        Objects.equals(this.mode, trendsWidgetEventRequest.mode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventBody, eventType, mode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrendsWidgetEventRequest {\n");
    sb.append("    eventBody: ").append(toIndentedString(eventBody)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("event_body", "event_type", "mode"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("event_body", "event_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TrendsWidgetEventRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TrendsWidgetEventRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TrendsWidgetEventRequest is not found in the empty JSON string", TrendsWidgetEventRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TrendsWidgetEventRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TrendsWidgetEventRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TrendsWidgetEventRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      // validate the required field `event_type`
      EventTypeEnum.validateJsonElement(jsonObj.get("event_type"));
      if ((jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) && !jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      // validate the optional field `mode`
      if (jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) {
        ModeEnum.validateJsonElement(jsonObj.get("mode"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrendsWidgetEventRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrendsWidgetEventRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrendsWidgetEventRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrendsWidgetEventRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TrendsWidgetEventRequest>() {
           @Override
           public void write(JsonWriter out, TrendsWidgetEventRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TrendsWidgetEventRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TrendsWidgetEventRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TrendsWidgetEventRequest
   * @throws IOException if the JSON string is invalid with respect to TrendsWidgetEventRequest
   */
  public static TrendsWidgetEventRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrendsWidgetEventRequest.class);
  }

  /**
   * Convert an instance of TrendsWidgetEventRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

