/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1AffiliatesLinksBulkPost202Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1AffiliatesLinksBulkPost202Response {
  public static final String SERIALIZED_NAME_JOB_ID = "job_id";
  @SerializedName(SERIALIZED_NAME_JOB_ID)
  @javax.annotation.Nullable
  private UUID jobId;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nullable
  private String mode;

  public static final String SERIALIZED_NAME_POLL_URL = "poll_url";
  @SerializedName(SERIALIZED_NAME_POLL_URL)
  @javax.annotation.Nullable
  private String pollUrl;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_SUBMITTED_ROWS = "submitted_rows";
  @SerializedName(SERIALIZED_NAME_SUBMITTED_ROWS)
  @javax.annotation.Nullable
  private Integer submittedRows;

  public V1AffiliatesLinksBulkPost202Response() {
  }

  public V1AffiliatesLinksBulkPost202Response jobId(@javax.annotation.Nullable UUID jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Get jobId
   * @return jobId
   */
  @javax.annotation.Nullable
  public UUID getJobId() {
    return jobId;
  }

  public void setJobId(@javax.annotation.Nullable UUID jobId) {
    this.jobId = jobId;
  }


  public V1AffiliatesLinksBulkPost202Response mode(@javax.annotation.Nullable String mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @javax.annotation.Nullable
  public String getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nullable String mode) {
    this.mode = mode;
  }


  public V1AffiliatesLinksBulkPost202Response pollUrl(@javax.annotation.Nullable String pollUrl) {
    this.pollUrl = pollUrl;
    return this;
  }

  /**
   * Get pollUrl
   * @return pollUrl
   */
  @javax.annotation.Nullable
  public String getPollUrl() {
    return pollUrl;
  }

  public void setPollUrl(@javax.annotation.Nullable String pollUrl) {
    this.pollUrl = pollUrl;
  }


  public V1AffiliatesLinksBulkPost202Response status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public V1AffiliatesLinksBulkPost202Response submittedRows(@javax.annotation.Nullable Integer submittedRows) {
    this.submittedRows = submittedRows;
    return this;
  }

  /**
   * Get submittedRows
   * @return submittedRows
   */
  @javax.annotation.Nullable
  public Integer getSubmittedRows() {
    return submittedRows;
  }

  public void setSubmittedRows(@javax.annotation.Nullable Integer submittedRows) {
    this.submittedRows = submittedRows;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AffiliatesLinksBulkPost202Response v1AffiliatesLinksBulkPost202Response = (V1AffiliatesLinksBulkPost202Response) o;
    return Objects.equals(this.jobId, v1AffiliatesLinksBulkPost202Response.jobId) &&
        Objects.equals(this.mode, v1AffiliatesLinksBulkPost202Response.mode) &&
        Objects.equals(this.pollUrl, v1AffiliatesLinksBulkPost202Response.pollUrl) &&
        Objects.equals(this.status, v1AffiliatesLinksBulkPost202Response.status) &&
        Objects.equals(this.submittedRows, v1AffiliatesLinksBulkPost202Response.submittedRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobId, mode, pollUrl, status, submittedRows);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AffiliatesLinksBulkPost202Response {\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    pollUrl: ").append(toIndentedString(pollUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submittedRows: ").append(toIndentedString(submittedRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("job_id", "mode", "poll_url", "status", "submitted_rows"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1AffiliatesLinksBulkPost202Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1AffiliatesLinksBulkPost202Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1AffiliatesLinksBulkPost202Response is not found in the empty JSON string", V1AffiliatesLinksBulkPost202Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1AffiliatesLinksBulkPost202Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1AffiliatesLinksBulkPost202Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("job_id") != null && !jsonObj.get("job_id").isJsonNull()) && !jsonObj.get("job_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `job_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("job_id").toString()));
      }
      if ((jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) && !jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      if ((jsonObj.get("poll_url") != null && !jsonObj.get("poll_url").isJsonNull()) && !jsonObj.get("poll_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `poll_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("poll_url").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1AffiliatesLinksBulkPost202Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1AffiliatesLinksBulkPost202Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1AffiliatesLinksBulkPost202Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1AffiliatesLinksBulkPost202Response.class));

       return (TypeAdapter<T>) new TypeAdapter<V1AffiliatesLinksBulkPost202Response>() {
           @Override
           public void write(JsonWriter out, V1AffiliatesLinksBulkPost202Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1AffiliatesLinksBulkPost202Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1AffiliatesLinksBulkPost202Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1AffiliatesLinksBulkPost202Response
   * @throws IOException if the JSON string is invalid with respect to V1AffiliatesLinksBulkPost202Response
   */
  public static V1AffiliatesLinksBulkPost202Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1AffiliatesLinksBulkPost202Response.class);
  }

  /**
   * Convert an instance of V1AffiliatesLinksBulkPost202Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

