/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1AffiliatesEventsPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1AffiliatesEventsPostRequest {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nonnull
  private String countryCode;

  /**
   * Gets or Sets deviceType
   */
  @JsonAdapter(DeviceTypeEnum.Adapter.class)
  public enum DeviceTypeEnum {
    IOS("ios"),
    
    ANDROID("android"),
    
    DESKTOP("desktop");

    private String value;

    DeviceTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeviceTypeEnum fromValue(String value) {
      for (DeviceTypeEnum b : DeviceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DeviceTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeviceTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeviceTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DeviceTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DeviceTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEVICE_TYPE = "device_type";
  @SerializedName(SERIALIZED_NAME_DEVICE_TYPE)
  @javax.annotation.Nullable
  private DeviceTypeEnum deviceType;

  /**
   * Gets or Sets eventType
   */
  @JsonAdapter(EventTypeEnum.Adapter.class)
  public enum EventTypeEnum {
    IMPRESSION("impression"),
    
    CLICK("click");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EventTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EventTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EventTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nonnull
  private EventTypeEnum eventType;

  public static final String SERIALIZED_NAME_OFFER_CAMPAIGN = "offer_campaign";
  @SerializedName(SERIALIZED_NAME_OFFER_CAMPAIGN)
  @javax.annotation.Nullable
  private String offerCampaign;

  public static final String SERIALIZED_NAME_OFFER_ID = "offer_id";
  @SerializedName(SERIALIZED_NAME_OFFER_ID)
  @javax.annotation.Nonnull
  private UUID offerId;

  public static final String SERIALIZED_NAME_OFFER_LABEL = "offer_label";
  @SerializedName(SERIALIZED_NAME_OFFER_LABEL)
  @javax.annotation.Nullable
  private String offerLabel;

  public static final String SERIALIZED_NAME_OPERATOR_ID = "operator_id";
  @SerializedName(SERIALIZED_NAME_OPERATOR_ID)
  @javax.annotation.Nonnull
  private Long operatorId;

  public static final String SERIALIZED_NAME_SESSION_TOKEN = "session_token";
  @SerializedName(SERIALIZED_NAME_SESSION_TOKEN)
  @javax.annotation.Nullable
  private String sessionToken;

  public static final String SERIALIZED_NAME_SUBNATIONAL_REGION_CODE = "subnational_region_code";
  @SerializedName(SERIALIZED_NAME_SUBNATIONAL_REGION_CODE)
  @javax.annotation.Nullable
  private String subnationalRegionCode;

  public V1AffiliatesEventsPostRequest() {
  }

  public V1AffiliatesEventsPostRequest countryCode(@javax.annotation.Nonnull String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   */
  @javax.annotation.Nonnull
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nonnull String countryCode) {
    this.countryCode = countryCode;
  }


  public V1AffiliatesEventsPostRequest deviceType(@javax.annotation.Nullable DeviceTypeEnum deviceType) {
    this.deviceType = deviceType;
    return this;
  }

  /**
   * Get deviceType
   * @return deviceType
   */
  @javax.annotation.Nullable
  public DeviceTypeEnum getDeviceType() {
    return deviceType;
  }

  public void setDeviceType(@javax.annotation.Nullable DeviceTypeEnum deviceType) {
    this.deviceType = deviceType;
  }


  public V1AffiliatesEventsPostRequest eventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nonnull
  public EventTypeEnum getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public V1AffiliatesEventsPostRequest offerCampaign(@javax.annotation.Nullable String offerCampaign) {
    this.offerCampaign = offerCampaign;
    return this;
  }

  /**
   * Get offerCampaign
   * @return offerCampaign
   */
  @javax.annotation.Nullable
  public String getOfferCampaign() {
    return offerCampaign;
  }

  public void setOfferCampaign(@javax.annotation.Nullable String offerCampaign) {
    this.offerCampaign = offerCampaign;
  }


  public V1AffiliatesEventsPostRequest offerId(@javax.annotation.Nonnull UUID offerId) {
    this.offerId = offerId;
    return this;
  }

  /**
   * Get offerId
   * @return offerId
   */
  @javax.annotation.Nonnull
  public UUID getOfferId() {
    return offerId;
  }

  public void setOfferId(@javax.annotation.Nonnull UUID offerId) {
    this.offerId = offerId;
  }


  public V1AffiliatesEventsPostRequest offerLabel(@javax.annotation.Nullable String offerLabel) {
    this.offerLabel = offerLabel;
    return this;
  }

  /**
   * Get offerLabel
   * @return offerLabel
   */
  @javax.annotation.Nullable
  public String getOfferLabel() {
    return offerLabel;
  }

  public void setOfferLabel(@javax.annotation.Nullable String offerLabel) {
    this.offerLabel = offerLabel;
  }


  public V1AffiliatesEventsPostRequest operatorId(@javax.annotation.Nonnull Long operatorId) {
    this.operatorId = operatorId;
    return this;
  }

  /**
   * Get operatorId
   * minimum: 1
   * @return operatorId
   */
  @javax.annotation.Nonnull
  public Long getOperatorId() {
    return operatorId;
  }

  public void setOperatorId(@javax.annotation.Nonnull Long operatorId) {
    this.operatorId = operatorId;
  }


  public V1AffiliatesEventsPostRequest sessionToken(@javax.annotation.Nullable String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

  /**
   * Get sessionToken
   * @return sessionToken
   */
  @javax.annotation.Nullable
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(@javax.annotation.Nullable String sessionToken) {
    this.sessionToken = sessionToken;
  }


  public V1AffiliatesEventsPostRequest subnationalRegionCode(@javax.annotation.Nullable String subnationalRegionCode) {
    this.subnationalRegionCode = subnationalRegionCode;
    return this;
  }

  /**
   * Get subnationalRegionCode
   * @return subnationalRegionCode
   */
  @javax.annotation.Nullable
  public String getSubnationalRegionCode() {
    return subnationalRegionCode;
  }

  public void setSubnationalRegionCode(@javax.annotation.Nullable String subnationalRegionCode) {
    this.subnationalRegionCode = subnationalRegionCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AffiliatesEventsPostRequest v1AffiliatesEventsPostRequest = (V1AffiliatesEventsPostRequest) o;
    return Objects.equals(this.countryCode, v1AffiliatesEventsPostRequest.countryCode) &&
        Objects.equals(this.deviceType, v1AffiliatesEventsPostRequest.deviceType) &&
        Objects.equals(this.eventType, v1AffiliatesEventsPostRequest.eventType) &&
        Objects.equals(this.offerCampaign, v1AffiliatesEventsPostRequest.offerCampaign) &&
        Objects.equals(this.offerId, v1AffiliatesEventsPostRequest.offerId) &&
        Objects.equals(this.offerLabel, v1AffiliatesEventsPostRequest.offerLabel) &&
        Objects.equals(this.operatorId, v1AffiliatesEventsPostRequest.operatorId) &&
        Objects.equals(this.sessionToken, v1AffiliatesEventsPostRequest.sessionToken) &&
        Objects.equals(this.subnationalRegionCode, v1AffiliatesEventsPostRequest.subnationalRegionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, deviceType, eventType, offerCampaign, offerId, offerLabel, operatorId, sessionToken, subnationalRegionCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AffiliatesEventsPostRequest {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    offerCampaign: ").append(toIndentedString(offerCampaign)).append("\n");
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    offerLabel: ").append(toIndentedString(offerLabel)).append("\n");
    sb.append("    operatorId: ").append(toIndentedString(operatorId)).append("\n");
    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    subnationalRegionCode: ").append(toIndentedString(subnationalRegionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country_code", "device_type", "event_type", "offer_campaign", "offer_id", "offer_label", "operator_id", "session_token", "subnational_region_code"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("country_code", "event_type", "offer_id", "operator_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1AffiliatesEventsPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1AffiliatesEventsPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1AffiliatesEventsPostRequest is not found in the empty JSON string", V1AffiliatesEventsPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1AffiliatesEventsPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1AffiliatesEventsPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1AffiliatesEventsPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("country_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code").toString()));
      }
      if ((jsonObj.get("device_type") != null && !jsonObj.get("device_type").isJsonNull()) && !jsonObj.get("device_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `device_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("device_type").toString()));
      }
      // validate the optional field `device_type`
      if (jsonObj.get("device_type") != null && !jsonObj.get("device_type").isJsonNull()) {
        DeviceTypeEnum.validateJsonElement(jsonObj.get("device_type"));
      }
      if (!jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      // validate the required field `event_type`
      EventTypeEnum.validateJsonElement(jsonObj.get("event_type"));
      if ((jsonObj.get("offer_campaign") != null && !jsonObj.get("offer_campaign").isJsonNull()) && !jsonObj.get("offer_campaign").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `offer_campaign` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offer_campaign").toString()));
      }
      if (!jsonObj.get("offer_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `offer_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offer_id").toString()));
      }
      if ((jsonObj.get("offer_label") != null && !jsonObj.get("offer_label").isJsonNull()) && !jsonObj.get("offer_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `offer_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offer_label").toString()));
      }
      if ((jsonObj.get("session_token") != null && !jsonObj.get("session_token").isJsonNull()) && !jsonObj.get("session_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `session_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("session_token").toString()));
      }
      if ((jsonObj.get("subnational_region_code") != null && !jsonObj.get("subnational_region_code").isJsonNull()) && !jsonObj.get("subnational_region_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subnational_region_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subnational_region_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1AffiliatesEventsPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1AffiliatesEventsPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1AffiliatesEventsPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1AffiliatesEventsPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V1AffiliatesEventsPostRequest>() {
           @Override
           public void write(JsonWriter out, V1AffiliatesEventsPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1AffiliatesEventsPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1AffiliatesEventsPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1AffiliatesEventsPostRequest
   * @throws IOException if the JSON string is invalid with respect to V1AffiliatesEventsPostRequest
   */
  public static V1AffiliatesEventsPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1AffiliatesEventsPostRequest.class);
  }

  /**
   * Convert an instance of V1AffiliatesEventsPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

