/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1AffiliatesParlayPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1AffiliatesParlayPostRequest {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode = "US";

  public static final String SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_IDS = "event_betting_market_position_ids";
  @SerializedName(SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_IDS)
  @javax.annotation.Nonnull
  private List<Long> eventBettingMarketPositionIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_HIDE_OFFERS_LINKS = "hide_offers_links";
  @SerializedName(SERIALIZED_NAME_HIDE_OFFERS_LINKS)
  @javax.annotation.Nullable
  private Boolean hideOffersLinks;

  /**
   * Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
   */
  @JsonAdapter(OddsFormatEnum.Adapter.class)
  public enum OddsFormatEnum {
    AMERICAN("american"),
    
    DECIMAL("decimal"),
    
    FRACTIONAL("fractional"),
    
    MULTIPLIER("multiplier"),
    
    PERCENT("percent");

    private String value;

    OddsFormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OddsFormatEnum fromValue(String value) {
      for (OddsFormatEnum b : OddsFormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OddsFormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OddsFormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OddsFormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OddsFormatEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OddsFormatEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ODDS_FORMAT = "odds_format";
  @SerializedName(SERIALIZED_NAME_ODDS_FORMAT)
  @javax.annotation.Nullable
  private OddsFormatEnum oddsFormat;

  public static final String SERIALIZED_NAME_OFFER_CAMPAIGN = "offer_campaign";
  @SerializedName(SERIALIZED_NAME_OFFER_CAMPAIGN)
  @javax.annotation.Nullable
  private String offerCampaign;

  public static final String SERIALIZED_NAME_OPERATOR_IDS = "operator_ids";
  @SerializedName(SERIALIZED_NAME_OPERATOR_IDS)
  @javax.annotation.Nullable
  private List<Long> operatorIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_OPERATOR_KEYS = "operator_keys";
  @SerializedName(SERIALIZED_NAME_OPERATOR_KEYS)
  @javax.annotation.Nullable
  private List<String> operatorKeys = new ArrayList<>();

  /**
   * Display mode. dfs rewrites leg stat lines to MORE/LESS.
   */
  @JsonAdapter(ProductModeEnum.Adapter.class)
  public enum ProductModeEnum {
    SPORTSBOOK("sportsbook"),
    
    DFS("dfs"),
    
    PREDICTION_MARKET("prediction_market");

    private String value;

    ProductModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProductModeEnum fromValue(String value) {
      for (ProductModeEnum b : ProductModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProductModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProductModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProductModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProductModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProductModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRODUCT_MODE = "product_mode";
  @SerializedName(SERIALIZED_NAME_PRODUCT_MODE)
  @javax.annotation.Nullable
  private ProductModeEnum productMode;

  public static final String SERIALIZED_NAME_SUBNATIONAL_REGION_CODE = "subnational_region_code";
  @SerializedName(SERIALIZED_NAME_SUBNATIONAL_REGION_CODE)
  @javax.annotation.Nullable
  private String subnationalRegionCode;

  public V1AffiliatesParlayPostRequest() {
  }

  public V1AffiliatesParlayPostRequest countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 country code.
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public V1AffiliatesParlayPostRequest eventBettingMarketPositionIds(@javax.annotation.Nonnull List<Long> eventBettingMarketPositionIds) {
    this.eventBettingMarketPositionIds = eventBettingMarketPositionIds;
    return this;
  }

  public V1AffiliatesParlayPostRequest addEventBettingMarketPositionIdsItem(Long eventBettingMarketPositionIdsItem) {
    if (this.eventBettingMarketPositionIds == null) {
      this.eventBettingMarketPositionIds = new ArrayList<>();
    }
    this.eventBettingMarketPositionIds.add(eventBettingMarketPositionIdsItem);
    return this;
  }

  /**
   * The event betting market positions that make up the parlay legs.
   * @return eventBettingMarketPositionIds
   */
  @javax.annotation.Nonnull
  public List<Long> getEventBettingMarketPositionIds() {
    return eventBettingMarketPositionIds;
  }

  public void setEventBettingMarketPositionIds(@javax.annotation.Nonnull List<Long> eventBettingMarketPositionIds) {
    this.eventBettingMarketPositionIds = eventBettingMarketPositionIds;
  }


  public V1AffiliatesParlayPostRequest hideOffersLinks(@javax.annotation.Nullable Boolean hideOffersLinks) {
    this.hideOffersLinks = hideOffersLinks;
    return this;
  }

  /**
   * When true, offer metadata is returned without the deep-link URLs.
   * @return hideOffersLinks
   */
  @javax.annotation.Nullable
  public Boolean getHideOffersLinks() {
    return hideOffersLinks;
  }

  public void setHideOffersLinks(@javax.annotation.Nullable Boolean hideOffersLinks) {
    this.hideOffersLinks = hideOffersLinks;
  }


  public V1AffiliatesParlayPostRequest oddsFormat(@javax.annotation.Nullable OddsFormatEnum oddsFormat) {
    this.oddsFormat = oddsFormat;
    return this;
  }

  /**
   * Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
   * @return oddsFormat
   */
  @javax.annotation.Nullable
  public OddsFormatEnum getOddsFormat() {
    return oddsFormat;
  }

  public void setOddsFormat(@javax.annotation.Nullable OddsFormatEnum oddsFormat) {
    this.oddsFormat = oddsFormat;
  }


  public V1AffiliatesParlayPostRequest offerCampaign(@javax.annotation.Nullable String offerCampaign) {
    this.offerCampaign = offerCampaign;
    return this;
  }

  /**
   * Optional campaign filter. Renders only offers tagged with this campaign.
   * @return offerCampaign
   */
  @javax.annotation.Nullable
  public String getOfferCampaign() {
    return offerCampaign;
  }

  public void setOfferCampaign(@javax.annotation.Nullable String offerCampaign) {
    this.offerCampaign = offerCampaign;
  }


  public V1AffiliatesParlayPostRequest operatorIds(@javax.annotation.Nullable List<Long> operatorIds) {
    this.operatorIds = operatorIds;
    return this;
  }

  public V1AffiliatesParlayPostRequest addOperatorIdsItem(Long operatorIdsItem) {
    if (this.operatorIds == null) {
      this.operatorIds = new ArrayList<>();
    }
    this.operatorIds.add(operatorIdsItem);
    return this;
  }

  /**
   * Optional list of operator IDs to gate which operators appear in the cart.
   * @return operatorIds
   */
  @javax.annotation.Nullable
  public List<Long> getOperatorIds() {
    return operatorIds;
  }

  public void setOperatorIds(@javax.annotation.Nullable List<Long> operatorIds) {
    this.operatorIds = operatorIds;
  }


  public V1AffiliatesParlayPostRequest operatorKeys(@javax.annotation.Nullable List<String> operatorKeys) {
    this.operatorKeys = operatorKeys;
    return this;
  }

  public V1AffiliatesParlayPostRequest addOperatorKeysItem(String operatorKeysItem) {
    if (this.operatorKeys == null) {
      this.operatorKeys = new ArrayList<>();
    }
    this.operatorKeys.add(operatorKeysItem);
    return this;
  }

  /**
   * Optional operator external keys (e.g. &#39;draftkings&#39;). Resolved IDs are merged with operator_ids.
   * @return operatorKeys
   */
  @javax.annotation.Nullable
  public List<String> getOperatorKeys() {
    return operatorKeys;
  }

  public void setOperatorKeys(@javax.annotation.Nullable List<String> operatorKeys) {
    this.operatorKeys = operatorKeys;
  }


  public V1AffiliatesParlayPostRequest productMode(@javax.annotation.Nullable ProductModeEnum productMode) {
    this.productMode = productMode;
    return this;
  }

  /**
   * Display mode. dfs rewrites leg stat lines to MORE/LESS.
   * @return productMode
   */
  @javax.annotation.Nullable
  public ProductModeEnum getProductMode() {
    return productMode;
  }

  public void setProductMode(@javax.annotation.Nullable ProductModeEnum productMode) {
    this.productMode = productMode;
  }


  public V1AffiliatesParlayPostRequest subnationalRegionCode(@javax.annotation.Nullable String subnationalRegionCode) {
    this.subnationalRegionCode = subnationalRegionCode;
    return this;
  }

  /**
   * ISO 3166-2 subnational region code (used for offer/deeplink resolution).
   * @return subnationalRegionCode
   */
  @javax.annotation.Nullable
  public String getSubnationalRegionCode() {
    return subnationalRegionCode;
  }

  public void setSubnationalRegionCode(@javax.annotation.Nullable String subnationalRegionCode) {
    this.subnationalRegionCode = subnationalRegionCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest = (V1AffiliatesParlayPostRequest) o;
    return Objects.equals(this.countryCode, v1AffiliatesParlayPostRequest.countryCode) &&
        Objects.equals(this.eventBettingMarketPositionIds, v1AffiliatesParlayPostRequest.eventBettingMarketPositionIds) &&
        Objects.equals(this.hideOffersLinks, v1AffiliatesParlayPostRequest.hideOffersLinks) &&
        Objects.equals(this.oddsFormat, v1AffiliatesParlayPostRequest.oddsFormat) &&
        Objects.equals(this.offerCampaign, v1AffiliatesParlayPostRequest.offerCampaign) &&
        Objects.equals(this.operatorIds, v1AffiliatesParlayPostRequest.operatorIds) &&
        Objects.equals(this.operatorKeys, v1AffiliatesParlayPostRequest.operatorKeys) &&
        Objects.equals(this.productMode, v1AffiliatesParlayPostRequest.productMode) &&
        Objects.equals(this.subnationalRegionCode, v1AffiliatesParlayPostRequest.subnationalRegionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, eventBettingMarketPositionIds, hideOffersLinks, oddsFormat, offerCampaign, operatorIds, operatorKeys, productMode, subnationalRegionCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AffiliatesParlayPostRequest {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    eventBettingMarketPositionIds: ").append(toIndentedString(eventBettingMarketPositionIds)).append("\n");
    sb.append("    hideOffersLinks: ").append(toIndentedString(hideOffersLinks)).append("\n");
    sb.append("    oddsFormat: ").append(toIndentedString(oddsFormat)).append("\n");
    sb.append("    offerCampaign: ").append(toIndentedString(offerCampaign)).append("\n");
    sb.append("    operatorIds: ").append(toIndentedString(operatorIds)).append("\n");
    sb.append("    operatorKeys: ").append(toIndentedString(operatorKeys)).append("\n");
    sb.append("    productMode: ").append(toIndentedString(productMode)).append("\n");
    sb.append("    subnationalRegionCode: ").append(toIndentedString(subnationalRegionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country_code", "event_betting_market_position_ids", "hide_offers_links", "odds_format", "offer_campaign", "operator_ids", "operator_keys", "product_mode", "subnational_region_code"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("event_betting_market_position_ids"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1AffiliatesParlayPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1AffiliatesParlayPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1AffiliatesParlayPostRequest is not found in the empty JSON string", V1AffiliatesParlayPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1AffiliatesParlayPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1AffiliatesParlayPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1AffiliatesParlayPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("country_code") != null && !jsonObj.get("country_code").isJsonNull()) && !jsonObj.get("country_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_code").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("event_betting_market_position_ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("event_betting_market_position_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_betting_market_position_ids` to be an array in the JSON string but got `%s`", jsonObj.get("event_betting_market_position_ids").toString()));
      }
      if ((jsonObj.get("odds_format") != null && !jsonObj.get("odds_format").isJsonNull()) && !jsonObj.get("odds_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `odds_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("odds_format").toString()));
      }
      // validate the optional field `odds_format`
      if (jsonObj.get("odds_format") != null && !jsonObj.get("odds_format").isJsonNull()) {
        OddsFormatEnum.validateJsonElement(jsonObj.get("odds_format"));
      }
      if ((jsonObj.get("offer_campaign") != null && !jsonObj.get("offer_campaign").isJsonNull()) && !jsonObj.get("offer_campaign").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `offer_campaign` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offer_campaign").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("operator_ids") != null && !jsonObj.get("operator_ids").isJsonNull() && !jsonObj.get("operator_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `operator_ids` to be an array in the JSON string but got `%s`", jsonObj.get("operator_ids").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("operator_keys") != null && !jsonObj.get("operator_keys").isJsonNull() && !jsonObj.get("operator_keys").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `operator_keys` to be an array in the JSON string but got `%s`", jsonObj.get("operator_keys").toString()));
      }
      if ((jsonObj.get("product_mode") != null && !jsonObj.get("product_mode").isJsonNull()) && !jsonObj.get("product_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `product_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product_mode").toString()));
      }
      // validate the optional field `product_mode`
      if (jsonObj.get("product_mode") != null && !jsonObj.get("product_mode").isJsonNull()) {
        ProductModeEnum.validateJsonElement(jsonObj.get("product_mode"));
      }
      if ((jsonObj.get("subnational_region_code") != null && !jsonObj.get("subnational_region_code").isJsonNull()) && !jsonObj.get("subnational_region_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subnational_region_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subnational_region_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1AffiliatesParlayPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1AffiliatesParlayPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1AffiliatesParlayPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1AffiliatesParlayPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V1AffiliatesParlayPostRequest>() {
           @Override
           public void write(JsonWriter out, V1AffiliatesParlayPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1AffiliatesParlayPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1AffiliatesParlayPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1AffiliatesParlayPostRequest
   * @throws IOException if the JSON string is invalid with respect to V1AffiliatesParlayPostRequest
   */
  public static V1AffiliatesParlayPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1AffiliatesParlayPostRequest.class);
  }

  /**
   * Convert an instance of V1AffiliatesParlayPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

