/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1EventsUpcomingEventsPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1EventsUpcomingEventsPostRequest {
  public static final String SERIALIZED_NAME_EVENT_DATE = "event_date";
  @SerializedName(SERIALIZED_NAME_EVENT_DATE)
  @javax.annotation.Nullable
  private LocalDate eventDate;

  public static final String SERIALIZED_NAME_LEAGUE_ID = "league_id";
  @SerializedName(SERIALIZED_NAME_LEAGUE_ID)
  @javax.annotation.Nullable
  private Long leagueId;

  public static final String SERIALIZED_NAME_LEAGUE_KEY = "league_key";
  @SerializedName(SERIALIZED_NAME_LEAGUE_KEY)
  @javax.annotation.Nullable
  private String leagueKey;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  @javax.annotation.Nullable
  private Long page = 1l;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Long pageSize = 100l;

  public static final String SERIALIZED_NAME_SPORT_ID = "sport_id";
  @SerializedName(SERIALIZED_NAME_SPORT_ID)
  @javax.annotation.Nullable
  private Long sportId;

  public static final String SERIALIZED_NAME_SPORT_KEY = "sport_key";
  @SerializedName(SERIALIZED_NAME_SPORT_KEY)
  @javax.annotation.Nullable
  private String sportKey;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone = "UTC";

  public V1EventsUpcomingEventsPostRequest() {
  }

  public V1EventsUpcomingEventsPostRequest eventDate(@javax.annotation.Nullable LocalDate eventDate) {
    this.eventDate = eventDate;
    return this;
  }

  /**
   * Filter by event date (YYYY-MM-DD). Defaults to today (UTC).
   * @return eventDate
   */
  @javax.annotation.Nullable
  public LocalDate getEventDate() {
    return eventDate;
  }

  public void setEventDate(@javax.annotation.Nullable LocalDate eventDate) {
    this.eventDate = eventDate;
  }


  public V1EventsUpcomingEventsPostRequest leagueId(@javax.annotation.Nullable Long leagueId) {
    this.leagueId = leagueId;
    return this;
  }

  /**
   * Get leagueId
   * minimum: 1
   * @return leagueId
   */
  @javax.annotation.Nullable
  public Long getLeagueId() {
    return leagueId;
  }

  public void setLeagueId(@javax.annotation.Nullable Long leagueId) {
    this.leagueId = leagueId;
  }


  public V1EventsUpcomingEventsPostRequest leagueKey(@javax.annotation.Nullable String leagueKey) {
    this.leagueKey = leagueKey;
    return this;
  }

  /**
   * League external key (e.g. &#39;nba&#39;, &#39;united-states.nba&#39;). Alternative to league_id. If both are provided, league_id takes precedence.
   * @return leagueKey
   */
  @javax.annotation.Nullable
  public String getLeagueKey() {
    return leagueKey;
  }

  public void setLeagueKey(@javax.annotation.Nullable String leagueKey) {
    this.leagueKey = leagueKey;
  }


  public V1EventsUpcomingEventsPostRequest page(@javax.annotation.Nullable Long page) {
    this.page = page;
    return this;
  }

  /**
   * Page number for pagination
   * minimum: 1
   * @return page
   */
  @javax.annotation.Nullable
  public Long getPage() {
    return page;
  }

  public void setPage(@javax.annotation.Nullable Long page) {
    this.page = page;
  }


  public V1EventsUpcomingEventsPostRequest pageSize(@javax.annotation.Nullable Long pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Number of events per page
   * minimum: 1
   * maximum: 100
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Long getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Long pageSize) {
    this.pageSize = pageSize;
  }


  public V1EventsUpcomingEventsPostRequest sportId(@javax.annotation.Nullable Long sportId) {
    this.sportId = sportId;
    return this;
  }

  /**
   * Get sportId
   * minimum: 1
   * @return sportId
   */
  @javax.annotation.Nullable
  public Long getSportId() {
    return sportId;
  }

  public void setSportId(@javax.annotation.Nullable Long sportId) {
    this.sportId = sportId;
  }


  public V1EventsUpcomingEventsPostRequest sportKey(@javax.annotation.Nullable String sportKey) {
    this.sportKey = sportKey;
    return this;
  }

  /**
   * Sport external key (e.g. &#39;american-football&#39;). Alternative to sport_id. If both are provided, sport_id takes precedence.
   * @return sportKey
   */
  @javax.annotation.Nullable
  public String getSportKey() {
    return sportKey;
  }

  public void setSportKey(@javax.annotation.Nullable String sportKey) {
    this.sportKey = sportKey;
  }


  public V1EventsUpcomingEventsPostRequest timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * IANA timezone for date interpretation (e.g. &#39;UTC&#39;, &#39;America/New_York&#39;, &#39;Europe/London&#39;)
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1EventsUpcomingEventsPostRequest v1EventsUpcomingEventsPostRequest = (V1EventsUpcomingEventsPostRequest) o;
    return Objects.equals(this.eventDate, v1EventsUpcomingEventsPostRequest.eventDate) &&
        Objects.equals(this.leagueId, v1EventsUpcomingEventsPostRequest.leagueId) &&
        Objects.equals(this.leagueKey, v1EventsUpcomingEventsPostRequest.leagueKey) &&
        Objects.equals(this.page, v1EventsUpcomingEventsPostRequest.page) &&
        Objects.equals(this.pageSize, v1EventsUpcomingEventsPostRequest.pageSize) &&
        Objects.equals(this.sportId, v1EventsUpcomingEventsPostRequest.sportId) &&
        Objects.equals(this.sportKey, v1EventsUpcomingEventsPostRequest.sportKey) &&
        Objects.equals(this.timezone, v1EventsUpcomingEventsPostRequest.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventDate, leagueId, leagueKey, page, pageSize, sportId, sportKey, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1EventsUpcomingEventsPostRequest {\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    leagueId: ").append(toIndentedString(leagueId)).append("\n");
    sb.append("    leagueKey: ").append(toIndentedString(leagueKey)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    sportId: ").append(toIndentedString(sportId)).append("\n");
    sb.append("    sportKey: ").append(toIndentedString(sportKey)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("event_date", "league_id", "league_key", "page", "page_size", "sport_id", "sport_key", "timezone"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1EventsUpcomingEventsPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1EventsUpcomingEventsPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1EventsUpcomingEventsPostRequest is not found in the empty JSON string", V1EventsUpcomingEventsPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1EventsUpcomingEventsPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1EventsUpcomingEventsPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("league_key") != null && !jsonObj.get("league_key").isJsonNull()) && !jsonObj.get("league_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `league_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("league_key").toString()));
      }
      if ((jsonObj.get("sport_key") != null && !jsonObj.get("sport_key").isJsonNull()) && !jsonObj.get("sport_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sport_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sport_key").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1EventsUpcomingEventsPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1EventsUpcomingEventsPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1EventsUpcomingEventsPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1EventsUpcomingEventsPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V1EventsUpcomingEventsPostRequest>() {
           @Override
           public void write(JsonWriter out, V1EventsUpcomingEventsPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1EventsUpcomingEventsPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1EventsUpcomingEventsPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1EventsUpcomingEventsPostRequest
   * @throws IOException if the JSON string is invalid with respect to V1EventsUpcomingEventsPostRequest
   */
  public static V1EventsUpcomingEventsPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1EventsUpcomingEventsPostRequest.class);
  }

  /**
   * Convert an instance of V1EventsUpcomingEventsPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

