/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1ReferencesTagTypesTagTypeIdChildrenGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1ReferencesTagTypesTagTypeIdChildrenGet200Response {
  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  @javax.annotation.Nullable
  private Object parent;

  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  @javax.annotation.Nullable
  private List<Object> records = new ArrayList<>();

  public V1ReferencesTagTypesTagTypeIdChildrenGet200Response() {
  }

  public V1ReferencesTagTypesTagTypeIdChildrenGet200Response parent(@javax.annotation.Nullable Object parent) {
    this.parent = parent;
    return this;
  }

  /**
   * Get parent
   * @return parent
   */
  @javax.annotation.Nullable
  public Object getParent() {
    return parent;
  }

  public void setParent(@javax.annotation.Nullable Object parent) {
    this.parent = parent;
  }


  public V1ReferencesTagTypesTagTypeIdChildrenGet200Response records(@javax.annotation.Nullable List<Object> records) {
    this.records = records;
    return this;
  }

  public V1ReferencesTagTypesTagTypeIdChildrenGet200Response addRecordsItem(Object recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   * @return records
   */
  @javax.annotation.Nullable
  public List<Object> getRecords() {
    return records;
  }

  public void setRecords(@javax.annotation.Nullable List<Object> records) {
    this.records = records;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ReferencesTagTypesTagTypeIdChildrenGet200Response v1ReferencesTagTypesTagTypeIdChildrenGet200Response = (V1ReferencesTagTypesTagTypeIdChildrenGet200Response) o;
    return Objects.equals(this.parent, v1ReferencesTagTypesTagTypeIdChildrenGet200Response.parent) &&
        Objects.equals(this.records, v1ReferencesTagTypesTagTypeIdChildrenGet200Response.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, records);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ReferencesTagTypesTagTypeIdChildrenGet200Response {\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("parent", "records"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1ReferencesTagTypesTagTypeIdChildrenGet200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1ReferencesTagTypesTagTypeIdChildrenGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1ReferencesTagTypesTagTypeIdChildrenGet200Response is not found in the empty JSON string", V1ReferencesTagTypesTagTypeIdChildrenGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1ReferencesTagTypesTagTypeIdChildrenGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1ReferencesTagTypesTagTypeIdChildrenGet200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("records") != null && !jsonObj.get("records").isJsonNull() && !jsonObj.get("records").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `records` to be an array in the JSON string but got `%s`", jsonObj.get("records").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1ReferencesTagTypesTagTypeIdChildrenGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1ReferencesTagTypesTagTypeIdChildrenGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1ReferencesTagTypesTagTypeIdChildrenGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1ReferencesTagTypesTagTypeIdChildrenGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<V1ReferencesTagTypesTagTypeIdChildrenGet200Response>() {
           @Override
           public void write(JsonWriter out, V1ReferencesTagTypesTagTypeIdChildrenGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1ReferencesTagTypesTagTypeIdChildrenGet200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1ReferencesTagTypesTagTypeIdChildrenGet200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1ReferencesTagTypesTagTypeIdChildrenGet200Response
   * @throws IOException if the JSON string is invalid with respect to V1ReferencesTagTypesTagTypeIdChildrenGet200Response
   */
  public static V1ReferencesTagTypesTagTypeIdChildrenGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1ReferencesTagTypesTagTypeIdChildrenGet200Response.class);
  }

  /**
   * Convert an instance of V1ReferencesTagTypesTagTypeIdChildrenGet200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

