/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.odditt.apiclient.JSON;

/**
 * V1TrendsByBettingMarketPositionPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class V1TrendsByBettingMarketPositionPostRequest {
  public static final String SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_IDS = "event_betting_market_position_ids";
  @SerializedName(SERIALIZED_NAME_EVENT_BETTING_MARKET_POSITION_IDS)
  @javax.annotation.Nonnull
  private List<Long> eventBettingMarketPositionIds = new ArrayList<>();

  /**
   * Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
   */
  @JsonAdapter(OddsFormatEnum.Adapter.class)
  public enum OddsFormatEnum {
    AMERICAN("american"),
    
    DECIMAL("decimal"),
    
    FRACTIONAL("fractional"),
    
    MULTIPLIER("multiplier"),
    
    PERCENT("percent");

    private String value;

    OddsFormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OddsFormatEnum fromValue(String value) {
      for (OddsFormatEnum b : OddsFormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OddsFormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OddsFormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OddsFormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OddsFormatEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OddsFormatEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ODDS_FORMAT = "odds_format";
  @SerializedName(SERIALIZED_NAME_ODDS_FORMAT)
  @javax.annotation.Nullable
  private OddsFormatEnum oddsFormat;

  /**
   * Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type&#x3D;player, positions [4,5]) unless an entity/position filter is set.
   */
  @JsonAdapter(ProductModeEnum.Adapter.class)
  public enum ProductModeEnum {
    SPORTSBOOK("sportsbook"),
    
    DFS("dfs"),
    
    PREDICTION_MARKET("prediction_market");

    private String value;

    ProductModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProductModeEnum fromValue(String value) {
      for (ProductModeEnum b : ProductModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProductModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProductModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProductModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProductModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProductModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRODUCT_MODE = "product_mode";
  @SerializedName(SERIALIZED_NAME_PRODUCT_MODE)
  @javax.annotation.Nullable
  private ProductModeEnum productMode;

  public static final String SERIALIZED_NAME_USE_CARTOON_IMAGES = "use_cartoon_images";
  @SerializedName(SERIALIZED_NAME_USE_CARTOON_IMAGES)
  @javax.annotation.Nullable
  private Boolean useCartoonImages;

  public V1TrendsByBettingMarketPositionPostRequest() {
  }

  public V1TrendsByBettingMarketPositionPostRequest eventBettingMarketPositionIds(@javax.annotation.Nonnull List<Long> eventBettingMarketPositionIds) {
    this.eventBettingMarketPositionIds = eventBettingMarketPositionIds;
    return this;
  }

  public V1TrendsByBettingMarketPositionPostRequest addEventBettingMarketPositionIdsItem(Long eventBettingMarketPositionIdsItem) {
    if (this.eventBettingMarketPositionIds == null) {
      this.eventBettingMarketPositionIds = new ArrayList<>();
    }
    this.eventBettingMarketPositionIds.add(eventBettingMarketPositionIdsItem);
    return this;
  }

  /**
   * Array of event betting market position IDs
   * @return eventBettingMarketPositionIds
   */
  @javax.annotation.Nonnull
  public List<Long> getEventBettingMarketPositionIds() {
    return eventBettingMarketPositionIds;
  }

  public void setEventBettingMarketPositionIds(@javax.annotation.Nonnull List<Long> eventBettingMarketPositionIds) {
    this.eventBettingMarketPositionIds = eventBettingMarketPositionIds;
  }


  public V1TrendsByBettingMarketPositionPostRequest oddsFormat(@javax.annotation.Nullable OddsFormatEnum oddsFormat) {
    this.oddsFormat = oddsFormat;
    return this;
  }

  /**
   * Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
   * @return oddsFormat
   */
  @javax.annotation.Nullable
  public OddsFormatEnum getOddsFormat() {
    return oddsFormat;
  }

  public void setOddsFormat(@javax.annotation.Nullable OddsFormatEnum oddsFormat) {
    this.oddsFormat = oddsFormat;
  }


  public V1TrendsByBettingMarketPositionPostRequest productMode(@javax.annotation.Nullable ProductModeEnum productMode) {
    this.productMode = productMode;
    return this;
  }

  /**
   * Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type&#x3D;player, positions [4,5]) unless an entity/position filter is set.
   * @return productMode
   */
  @javax.annotation.Nullable
  public ProductModeEnum getProductMode() {
    return productMode;
  }

  public void setProductMode(@javax.annotation.Nullable ProductModeEnum productMode) {
    this.productMode = productMode;
  }


  public V1TrendsByBettingMarketPositionPostRequest useCartoonImages(@javax.annotation.Nullable Boolean useCartoonImages) {
    this.useCartoonImages = useCartoonImages;
    return this;
  }

  /**
   * When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
   * @return useCartoonImages
   */
  @javax.annotation.Nullable
  public Boolean getUseCartoonImages() {
    return useCartoonImages;
  }

  public void setUseCartoonImages(@javax.annotation.Nullable Boolean useCartoonImages) {
    this.useCartoonImages = useCartoonImages;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TrendsByBettingMarketPositionPostRequest v1TrendsByBettingMarketPositionPostRequest = (V1TrendsByBettingMarketPositionPostRequest) o;
    return Objects.equals(this.eventBettingMarketPositionIds, v1TrendsByBettingMarketPositionPostRequest.eventBettingMarketPositionIds) &&
        Objects.equals(this.oddsFormat, v1TrendsByBettingMarketPositionPostRequest.oddsFormat) &&
        Objects.equals(this.productMode, v1TrendsByBettingMarketPositionPostRequest.productMode) &&
        Objects.equals(this.useCartoonImages, v1TrendsByBettingMarketPositionPostRequest.useCartoonImages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventBettingMarketPositionIds, oddsFormat, productMode, useCartoonImages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TrendsByBettingMarketPositionPostRequest {\n");
    sb.append("    eventBettingMarketPositionIds: ").append(toIndentedString(eventBettingMarketPositionIds)).append("\n");
    sb.append("    oddsFormat: ").append(toIndentedString(oddsFormat)).append("\n");
    sb.append("    productMode: ").append(toIndentedString(productMode)).append("\n");
    sb.append("    useCartoonImages: ").append(toIndentedString(useCartoonImages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("event_betting_market_position_ids", "odds_format", "product_mode", "use_cartoon_images"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("event_betting_market_position_ids"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V1TrendsByBettingMarketPositionPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V1TrendsByBettingMarketPositionPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V1TrendsByBettingMarketPositionPostRequest is not found in the empty JSON string", V1TrendsByBettingMarketPositionPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V1TrendsByBettingMarketPositionPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V1TrendsByBettingMarketPositionPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1TrendsByBettingMarketPositionPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("event_betting_market_position_ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("event_betting_market_position_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_betting_market_position_ids` to be an array in the JSON string but got `%s`", jsonObj.get("event_betting_market_position_ids").toString()));
      }
      if ((jsonObj.get("odds_format") != null && !jsonObj.get("odds_format").isJsonNull()) && !jsonObj.get("odds_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `odds_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("odds_format").toString()));
      }
      // validate the optional field `odds_format`
      if (jsonObj.get("odds_format") != null && !jsonObj.get("odds_format").isJsonNull()) {
        OddsFormatEnum.validateJsonElement(jsonObj.get("odds_format"));
      }
      if ((jsonObj.get("product_mode") != null && !jsonObj.get("product_mode").isJsonNull()) && !jsonObj.get("product_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `product_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product_mode").toString()));
      }
      // validate the optional field `product_mode`
      if (jsonObj.get("product_mode") != null && !jsonObj.get("product_mode").isJsonNull()) {
        ProductModeEnum.validateJsonElement(jsonObj.get("product_mode"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1TrendsByBettingMarketPositionPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1TrendsByBettingMarketPositionPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1TrendsByBettingMarketPositionPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1TrendsByBettingMarketPositionPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V1TrendsByBettingMarketPositionPostRequest>() {
           @Override
           public void write(JsonWriter out, V1TrendsByBettingMarketPositionPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1TrendsByBettingMarketPositionPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V1TrendsByBettingMarketPositionPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V1TrendsByBettingMarketPositionPostRequest
   * @throws IOException if the JSON string is invalid with respect to V1TrendsByBettingMarketPositionPostRequest
   */
  public static V1TrendsByBettingMarketPositionPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1TrendsByBettingMarketPositionPostRequest.class);
  }

  /**
   * Convert an instance of V1TrendsByBettingMarketPositionPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

