/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiCallback;
import com.odditt.apiclient.ApiClient;
import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.ApiResponse;
import com.odditt.apiclient.Configuration;
import com.odditt.apiclient.Pair;
import com.odditt.apiclient.ProgressRequestBody;
import com.odditt.apiclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.odditt.apiclient.model.AffiliateErrorResponse;
import com.odditt.apiclient.model.V1AffiliatesEventPositionPostRequest;
import com.odditt.apiclient.model.V1AffiliatesParlayPostRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AffiliatesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AffiliatesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AffiliatesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1AffiliatesEventPositionPost
     * @param v1AffiliatesEventPositionPostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesEventPositionPostCall(@javax.annotation.Nonnull V1AffiliatesEventPositionPostRequest v1AffiliatesEventPositionPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = v1AffiliatesEventPositionPostRequest;

        // create path and map variables
        String localVarPath = "/v1/affiliates/event-position";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1AffiliatesEventPositionPostValidateBeforeCall(@javax.annotation.Nonnull V1AffiliatesEventPositionPostRequest v1AffiliatesEventPositionPostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'v1AffiliatesEventPositionPostRequest' is set
        if (v1AffiliatesEventPositionPostRequest == null) {
            throw new ApiException("Missing the required parameter 'v1AffiliatesEventPositionPostRequest' when calling v1AffiliatesEventPositionPost(Async)");
        }

        return v1AffiliatesEventPositionPostCall(v1AffiliatesEventPositionPostRequest, _callback);

    }

    /**
     * Single-bet cart for affiliate mode
     * Returns live odds across operators for a single event betting market position, overlaid with the calling client&#39;s best affiliate offer per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a single selection. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesEventPositionPostRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1AffiliatesEventPositionPost(@javax.annotation.Nonnull V1AffiliatesEventPositionPostRequest v1AffiliatesEventPositionPostRequest) throws ApiException {
        ApiResponse<Object> localVarResp = v1AffiliatesEventPositionPostWithHttpInfo(v1AffiliatesEventPositionPostRequest);
        return localVarResp.getData();
    }

    /**
     * Single-bet cart for affiliate mode
     * Returns live odds across operators for a single event betting market position, overlaid with the calling client&#39;s best affiliate offer per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a single selection. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesEventPositionPostRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1AffiliatesEventPositionPostWithHttpInfo(@javax.annotation.Nonnull V1AffiliatesEventPositionPostRequest v1AffiliatesEventPositionPostRequest) throws ApiException {
        okhttp3.Call localVarCall = v1AffiliatesEventPositionPostValidateBeforeCall(v1AffiliatesEventPositionPostRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Single-bet cart for affiliate mode (asynchronously)
     * Returns live odds across operators for a single event betting market position, overlaid with the calling client&#39;s best affiliate offer per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a single selection. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesEventPositionPostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesEventPositionPostAsync(@javax.annotation.Nonnull V1AffiliatesEventPositionPostRequest v1AffiliatesEventPositionPostRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1AffiliatesEventPositionPostValidateBeforeCall(v1AffiliatesEventPositionPostRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1AffiliatesParlayPost
     * @param v1AffiliatesParlayPostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesParlayPostCall(@javax.annotation.Nonnull V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = v1AffiliatesParlayPostRequest;

        // create path and map variables
        String localVarPath = "/v1/affiliates/parlay";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1AffiliatesParlayPostValidateBeforeCall(@javax.annotation.Nonnull V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'v1AffiliatesParlayPostRequest' is set
        if (v1AffiliatesParlayPostRequest == null) {
            throw new ApiException("Missing the required parameter 'v1AffiliatesParlayPostRequest' when calling v1AffiliatesParlayPost(Async)");
        }

        return v1AffiliatesParlayPostCall(v1AffiliatesParlayPostRequest, _callback);

    }

    /**
     * Parlay cart for affiliate mode
     * Returns combined parlay odds per operator, the per-leg single bets, and the calling client&#39;s best affiliate offer per operator, with combo deeplinks generated per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a multi-leg bet. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesParlayPostRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1AffiliatesParlayPost(@javax.annotation.Nonnull V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest) throws ApiException {
        ApiResponse<Object> localVarResp = v1AffiliatesParlayPostWithHttpInfo(v1AffiliatesParlayPostRequest);
        return localVarResp.getData();
    }

    /**
     * Parlay cart for affiliate mode
     * Returns combined parlay odds per operator, the per-leg single bets, and the calling client&#39;s best affiliate offer per operator, with combo deeplinks generated per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a multi-leg bet. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesParlayPostRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1AffiliatesParlayPostWithHttpInfo(@javax.annotation.Nonnull V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest) throws ApiException {
        okhttp3.Call localVarCall = v1AffiliatesParlayPostValidateBeforeCall(v1AffiliatesParlayPostRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Parlay cart for affiliate mode (asynchronously)
     * Returns combined parlay odds per operator, the per-leg single bets, and the calling client&#39;s best affiliate offer per operator, with combo deeplinks generated per operator. Powers the widget&#39;s \&quot;Bet Now\&quot; cart for a multi-leg bet. Results are scoped to the authenticated client; operators can be gated with operator_ids / operator_keys.
     * @param v1AffiliatesParlayPostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesParlayPostAsync(@javax.annotation.Nonnull V1AffiliatesParlayPostRequest v1AffiliatesParlayPostRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1AffiliatesParlayPostValidateBeforeCall(v1AffiliatesParlayPostRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
