/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiCallback;
import com.odditt.apiclient.ApiClient;
import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.ApiResponse;
import com.odditt.apiclient.Configuration;
import com.odditt.apiclient.Pair;
import com.odditt.apiclient.ProgressRequestBody;
import com.odditt.apiclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import com.odditt.apiclient.model.TrendsErrorResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HistoricalApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public HistoricalApi() {
        this(Configuration.getDefaultApiClient());
    }

    public HistoricalApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1HistoricalEventsGet
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to v1)
     * @param sportId  (optional)
     * @param leagueId  (optional)
     * @param teamId Filter to events involving this team as either home or away. (optional)
     * @param startDate Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param endDate Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1HistoricalEventsGetCall(@javax.annotation.Nullable String schemaVersion, @javax.annotation.Nullable Long sportId, @javax.annotation.Nullable Long leagueId, @javax.annotation.Nullable Long teamId, @javax.annotation.Nullable String startDate, @javax.annotation.Nullable String endDate, @javax.annotation.Nullable Long page, @javax.annotation.Nullable Long pageSize, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/historical/events";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (schemaVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("schema_version", schemaVersion));
        }

        if (sportId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sport_id", sportId));
        }

        if (leagueId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("league_id", leagueId));
        }

        if (teamId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("team_id", teamId));
        }

        if (startDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start_date", startDate));
        }

        if (endDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("end_date", endDate));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1HistoricalEventsGetValidateBeforeCall(@javax.annotation.Nullable String schemaVersion, @javax.annotation.Nullable Long sportId, @javax.annotation.Nullable Long leagueId, @javax.annotation.Nullable Long teamId, @javax.annotation.Nullable String startDate, @javax.annotation.Nullable String endDate, @javax.annotation.Nullable Long page, @javax.annotation.Nullable Long pageSize, final ApiCallback _callback) throws ApiException {
        return v1HistoricalEventsGetCall(schemaVersion, sportId, leagueId, teamId, startDate, endDate, page, pageSize, _callback);

    }

    /**
     * List historical odds events (paginated)
     * Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive &#x60;403 Forbidden&#x60;. 
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to v1)
     * @param sportId  (optional)
     * @param leagueId  (optional)
     * @param teamId Filter to events involving this team as either home or away. (optional)
     * @param startDate Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param endDate Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 20)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1HistoricalEventsGet(@javax.annotation.Nullable String schemaVersion, @javax.annotation.Nullable Long sportId, @javax.annotation.Nullable Long leagueId, @javax.annotation.Nullable Long teamId, @javax.annotation.Nullable String startDate, @javax.annotation.Nullable String endDate, @javax.annotation.Nullable Long page, @javax.annotation.Nullable Long pageSize) throws ApiException {
        ApiResponse<Object> localVarResp = v1HistoricalEventsGetWithHttpInfo(schemaVersion, sportId, leagueId, teamId, startDate, endDate, page, pageSize);
        return localVarResp.getData();
    }

    /**
     * List historical odds events (paginated)
     * Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive &#x60;403 Forbidden&#x60;. 
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to v1)
     * @param sportId  (optional)
     * @param leagueId  (optional)
     * @param teamId Filter to events involving this team as either home or away. (optional)
     * @param startDate Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param endDate Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 20)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1HistoricalEventsGetWithHttpInfo(@javax.annotation.Nullable String schemaVersion, @javax.annotation.Nullable Long sportId, @javax.annotation.Nullable Long leagueId, @javax.annotation.Nullable Long teamId, @javax.annotation.Nullable String startDate, @javax.annotation.Nullable String endDate, @javax.annotation.Nullable Long page, @javax.annotation.Nullable Long pageSize) throws ApiException {
        okhttp3.Call localVarCall = v1HistoricalEventsGetValidateBeforeCall(schemaVersion, sportId, leagueId, teamId, startDate, endDate, page, pageSize, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List historical odds events (paginated) (asynchronously)
     * Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive &#x60;403 Forbidden&#x60;. 
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to v1)
     * @param sportId  (optional)
     * @param leagueId  (optional)
     * @param teamId Filter to events involving this team as either home or away. (optional)
     * @param startDate Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param endDate Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param page  (optional, default to 1)
     * @param pageSize  (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1HistoricalEventsGetAsync(@javax.annotation.Nullable String schemaVersion, @javax.annotation.Nullable Long sportId, @javax.annotation.Nullable Long leagueId, @javax.annotation.Nullable Long teamId, @javax.annotation.Nullable String startDate, @javax.annotation.Nullable String endDate, @javax.annotation.Nullable Long page, @javax.annotation.Nullable Long pageSize, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1HistoricalEventsGetValidateBeforeCall(schemaVersion, sportId, leagueId, teamId, startDate, endDate, page, pageSize, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1HistoricalOddsEventIdExtGet
     * @param eventId Canonical event identifier. (required)
     * @param ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to v1)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> File payload streamed back to the client. </td><td>  * Content-Disposition - Always &#x60;attachment; filename&#x3D;\&quot;event_&lt;event_id&gt;.&lt;ext&gt;\&quot;&#x60;. <br>  * ETag - Strong validator based on the SHA-256 of the file bytes-at-rest. <br>  </td></tr>
        <tr><td> 206 </td><td> Partial content when the client provided a &#x60;Range&#x60; header. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified — the client supplied a matching &#x60;If-None-Match&#x60;. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (invalid path/query parameter or JSON type mismatch in the body). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource does not exist. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Upstream content delivery unavailable. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1HistoricalOddsEventIdExtGetCall(@javax.annotation.Nonnull Long eventId, @javax.annotation.Nonnull String ext, @javax.annotation.Nullable String schemaVersion, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/historical/odds/{event_id}.{ext}"
            .replace("{" + "event_id" + "}", localVarApiClient.escapeString(eventId.toString()))
            .replace("{" + "ext" + "}", localVarApiClient.escapeString(ext.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (schemaVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("schema_version", schemaVersion));
        }

        final String[] localVarAccepts = {
            "application/json",
            "text/csv"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1HistoricalOddsEventIdExtGetValidateBeforeCall(@javax.annotation.Nonnull Long eventId, @javax.annotation.Nonnull String ext, @javax.annotation.Nullable String schemaVersion, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'eventId' is set
        if (eventId == null) {
            throw new ApiException("Missing the required parameter 'eventId' when calling v1HistoricalOddsEventIdExtGet(Async)");
        }

        // verify the required parameter 'ext' is set
        if (ext == null) {
            throw new ApiException("Missing the required parameter 'ext' when calling v1HistoricalOddsEventIdExtGet(Async)");
        }

        return v1HistoricalOddsEventIdExtGetCall(eventId, ext, schemaVersion, _callback);

    }

    /**
     * Download a per-event historical odds file
     * Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The &#x60;sha256&#x60; of the bytes-at-rest is exposed as a strong &#x60;ETag&#x60;. Clients can short-circuit with &#x60;If-None-Match&#x60; to receive &#x60;304 Not Modified&#x60;. &#x60;Range&#x60; requests are forwarded upstream and &#x60;206 Partial Content&#x60; responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
     * @param eventId Canonical event identifier. (required)
     * @param ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to v1)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> File payload streamed back to the client. </td><td>  * Content-Disposition - Always &#x60;attachment; filename&#x3D;\&quot;event_&lt;event_id&gt;.&lt;ext&gt;\&quot;&#x60;. <br>  * ETag - Strong validator based on the SHA-256 of the file bytes-at-rest. <br>  </td></tr>
        <tr><td> 206 </td><td> Partial content when the client provided a &#x60;Range&#x60; header. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified — the client supplied a matching &#x60;If-None-Match&#x60;. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (invalid path/query parameter or JSON type mismatch in the body). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource does not exist. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Upstream content delivery unavailable. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1HistoricalOddsEventIdExtGet(@javax.annotation.Nonnull Long eventId, @javax.annotation.Nonnull String ext, @javax.annotation.Nullable String schemaVersion) throws ApiException {
        ApiResponse<Object> localVarResp = v1HistoricalOddsEventIdExtGetWithHttpInfo(eventId, ext, schemaVersion);
        return localVarResp.getData();
    }

    /**
     * Download a per-event historical odds file
     * Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The &#x60;sha256&#x60; of the bytes-at-rest is exposed as a strong &#x60;ETag&#x60;. Clients can short-circuit with &#x60;If-None-Match&#x60; to receive &#x60;304 Not Modified&#x60;. &#x60;Range&#x60; requests are forwarded upstream and &#x60;206 Partial Content&#x60; responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
     * @param eventId Canonical event identifier. (required)
     * @param ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to v1)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> File payload streamed back to the client. </td><td>  * Content-Disposition - Always &#x60;attachment; filename&#x3D;\&quot;event_&lt;event_id&gt;.&lt;ext&gt;\&quot;&#x60;. <br>  * ETag - Strong validator based on the SHA-256 of the file bytes-at-rest. <br>  </td></tr>
        <tr><td> 206 </td><td> Partial content when the client provided a &#x60;Range&#x60; header. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified — the client supplied a matching &#x60;If-None-Match&#x60;. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (invalid path/query parameter or JSON type mismatch in the body). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource does not exist. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Upstream content delivery unavailable. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1HistoricalOddsEventIdExtGetWithHttpInfo(@javax.annotation.Nonnull Long eventId, @javax.annotation.Nonnull String ext, @javax.annotation.Nullable String schemaVersion) throws ApiException {
        okhttp3.Call localVarCall = v1HistoricalOddsEventIdExtGetValidateBeforeCall(eventId, ext, schemaVersion, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Download a per-event historical odds file (asynchronously)
     * Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The &#x60;sha256&#x60; of the bytes-at-rest is exposed as a strong &#x60;ETag&#x60;. Clients can short-circuit with &#x60;If-None-Match&#x60; to receive &#x60;304 Not Modified&#x60;. &#x60;Range&#x60; requests are forwarded upstream and &#x60;206 Partial Content&#x60; responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
     * @param eventId Canonical event identifier. (required)
     * @param ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param schemaVersion Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to v1)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> File payload streamed back to the client. </td><td>  * Content-Disposition - Always &#x60;attachment; filename&#x3D;\&quot;event_&lt;event_id&gt;.&lt;ext&gt;\&quot;&#x60;. <br>  * ETag - Strong validator based on the SHA-256 of the file bytes-at-rest. <br>  </td></tr>
        <tr><td> 206 </td><td> Partial content when the client provided a &#x60;Range&#x60; header. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified — the client supplied a matching &#x60;If-None-Match&#x60;. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed (invalid path/query parameter or JSON type mismatch in the body). </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid credentials. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource does not exist. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The request body was syntactically valid JSON but one or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Upstream content delivery unavailable. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1HistoricalOddsEventIdExtGetAsync(@javax.annotation.Nonnull Long eventId, @javax.annotation.Nonnull String ext, @javax.annotation.Nullable String schemaVersion, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1HistoricalOddsEventIdExtGetValidateBeforeCall(eventId, ext, schemaVersion, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
