/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiCallback;
import com.odditt.apiclient.ApiClient;
import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.ApiResponse;
import com.odditt.apiclient.Configuration;
import com.odditt.apiclient.Pair;
import com.odditt.apiclient.ProgressRequestBody;
import com.odditt.apiclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.odditt.apiclient.model.V1OddsUpcomingOddsByEventPostRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OddsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OddsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OddsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1OddsUpcomingOddsByEventPost
     * @param v1OddsUpcomingOddsByEventPostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1OddsUpcomingOddsByEventPostCall(@javax.annotation.Nonnull V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = v1OddsUpcomingOddsByEventPostRequest;

        // create path and map variables
        String localVarPath = "/v1/odds/upcoming-odds-by-event";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1OddsUpcomingOddsByEventPostValidateBeforeCall(@javax.annotation.Nonnull V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'v1OddsUpcomingOddsByEventPostRequest' is set
        if (v1OddsUpcomingOddsByEventPostRequest == null) {
            throw new ApiException("Missing the required parameter 'v1OddsUpcomingOddsByEventPostRequest' when calling v1OddsUpcomingOddsByEventPost(Async)");
        }

        return v1OddsUpcomingOddsByEventPostCall(v1OddsUpcomingOddsByEventPostRequest, _callback);

    }

    /**
     * Get upcoming odds by event
     * Returns paginated betting market positions for a specific upcoming event, optionally filtered by operator.
     * @param v1OddsUpcomingOddsByEventPostRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public Object v1OddsUpcomingOddsByEventPost(@javax.annotation.Nonnull V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest) throws ApiException {
        ApiResponse<Object> localVarResp = v1OddsUpcomingOddsByEventPostWithHttpInfo(v1OddsUpcomingOddsByEventPostRequest);
        return localVarResp.getData();
    }

    /**
     * Get upcoming odds by event
     * Returns paginated betting market positions for a specific upcoming event, optionally filtered by operator.
     * @param v1OddsUpcomingOddsByEventPostRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1OddsUpcomingOddsByEventPostWithHttpInfo(@javax.annotation.Nonnull V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest) throws ApiException {
        okhttp3.Call localVarCall = v1OddsUpcomingOddsByEventPostValidateBeforeCall(v1OddsUpcomingOddsByEventPostRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get upcoming odds by event (asynchronously)
     * Returns paginated betting market positions for a specific upcoming event, optionally filtered by operator.
     * @param v1OddsUpcomingOddsByEventPostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1OddsUpcomingOddsByEventPostAsync(@javax.annotation.Nonnull V1OddsUpcomingOddsByEventPostRequest v1OddsUpcomingOddsByEventPostRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1OddsUpcomingOddsByEventPostValidateBeforeCall(v1OddsUpcomingOddsByEventPostRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
