/*
 * Odditt B2B Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.odditt.apiclient.api;

import com.odditt.apiclient.ApiCallback;
import com.odditt.apiclient.ApiClient;
import com.odditt.apiclient.ApiException;
import com.odditt.apiclient.ApiResponse;
import com.odditt.apiclient.Configuration;
import com.odditt.apiclient.Pair;
import com.odditt.apiclient.ProgressRequestBody;
import com.odditt.apiclient.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.odditt.apiclient.model.AffiliateErrorResponse;
import java.time.LocalDate;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ReportingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ReportingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ReportingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1AffiliatesLinksClicksGet
     * @param startDate  (required)
     * @param endDate  (required)
     * @param operatorId  (optional)
     * @param countryCode  (optional)
     * @param subnationalRegionCode  (optional)
     * @param offerCampaign  (optional)
     * @param offerLabel  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesLinksClicksGetCall(@javax.annotation.Nonnull LocalDate startDate, @javax.annotation.Nonnull LocalDate endDate, @javax.annotation.Nullable Long operatorId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String subnationalRegionCode, @javax.annotation.Nullable String offerCampaign, @javax.annotation.Nullable String offerLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/affiliates/links/clicks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (startDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start_date", startDate));
        }

        if (endDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("end_date", endDate));
        }

        if (operatorId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("operator_id", operatorId));
        }

        if (countryCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country_code", countryCode));
        }

        if (subnationalRegionCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("subnational_region_code", subnationalRegionCode));
        }

        if (offerCampaign != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offer_campaign", offerCampaign));
        }

        if (offerLabel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offer_label", offerLabel));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1AffiliatesLinksClicksGetValidateBeforeCall(@javax.annotation.Nonnull LocalDate startDate, @javax.annotation.Nonnull LocalDate endDate, @javax.annotation.Nullable Long operatorId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String subnationalRegionCode, @javax.annotation.Nullable String offerCampaign, @javax.annotation.Nullable String offerLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'startDate' is set
        if (startDate == null) {
            throw new ApiException("Missing the required parameter 'startDate' when calling v1AffiliatesLinksClicksGet(Async)");
        }

        // verify the required parameter 'endDate' is set
        if (endDate == null) {
            throw new ApiException("Missing the required parameter 'endDate' when calling v1AffiliatesLinksClicksGet(Async)");
        }

        return v1AffiliatesLinksClicksGetCall(startDate, endDate, operatorId, countryCode, subnationalRegionCode, offerCampaign, offerLabel, _callback);

    }

    /**
     * Impression/click rollups
     * Per-link, per-day impression and click counts for the authenticated client.
     * @param startDate  (required)
     * @param endDate  (required)
     * @param operatorId  (optional)
     * @param countryCode  (optional)
     * @param subnationalRegionCode  (optional)
     * @param offerCampaign  (optional)
     * @param offerLabel  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1AffiliatesLinksClicksGet(@javax.annotation.Nonnull LocalDate startDate, @javax.annotation.Nonnull LocalDate endDate, @javax.annotation.Nullable Long operatorId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String subnationalRegionCode, @javax.annotation.Nullable String offerCampaign, @javax.annotation.Nullable String offerLabel) throws ApiException {
        ApiResponse<Object> localVarResp = v1AffiliatesLinksClicksGetWithHttpInfo(startDate, endDate, operatorId, countryCode, subnationalRegionCode, offerCampaign, offerLabel);
        return localVarResp.getData();
    }

    /**
     * Impression/click rollups
     * Per-link, per-day impression and click counts for the authenticated client.
     * @param startDate  (required)
     * @param endDate  (required)
     * @param operatorId  (optional)
     * @param countryCode  (optional)
     * @param subnationalRegionCode  (optional)
     * @param offerCampaign  (optional)
     * @param offerLabel  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1AffiliatesLinksClicksGetWithHttpInfo(@javax.annotation.Nonnull LocalDate startDate, @javax.annotation.Nonnull LocalDate endDate, @javax.annotation.Nullable Long operatorId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String subnationalRegionCode, @javax.annotation.Nullable String offerCampaign, @javax.annotation.Nullable String offerLabel) throws ApiException {
        okhttp3.Call localVarCall = v1AffiliatesLinksClicksGetValidateBeforeCall(startDate, endDate, operatorId, countryCode, subnationalRegionCode, offerCampaign, offerLabel, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Impression/click rollups (asynchronously)
     * Per-link, per-day impression and click counts for the authenticated client.
     * @param startDate  (required)
     * @param endDate  (required)
     * @param operatorId  (optional)
     * @param countryCode  (optional)
     * @param subnationalRegionCode  (optional)
     * @param offerCampaign  (optional)
     * @param offerLabel  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesLinksClicksGetAsync(@javax.annotation.Nonnull LocalDate startDate, @javax.annotation.Nonnull LocalDate endDate, @javax.annotation.Nullable Long operatorId, @javax.annotation.Nullable String countryCode, @javax.annotation.Nullable String subnationalRegionCode, @javax.annotation.Nullable String offerCampaign, @javax.annotation.Nullable String offerLabel, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1AffiliatesLinksClicksGetValidateBeforeCall(startDate, endDate, operatorId, countryCode, subnationalRegionCode, offerCampaign, offerLabel, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1AffiliatesLinksInventorySummaryGet
     * @param groupBy  (optional, default to operator)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesLinksInventorySummaryGetCall(@javax.annotation.Nullable String groupBy, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/affiliates/links/inventory-summary";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (groupBy != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("group_by", groupBy));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1AffiliatesLinksInventorySummaryGetValidateBeforeCall(@javax.annotation.Nullable String groupBy, final ApiCallback _callback) throws ApiException {
        return v1AffiliatesLinksInventorySummaryGetCall(groupBy, _callback);

    }

    /**
     * Inventory counts
     * Active/inactive link counts grouped by the requested dimension.
     * @param groupBy  (optional, default to operator)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public Object v1AffiliatesLinksInventorySummaryGet(@javax.annotation.Nullable String groupBy) throws ApiException {
        ApiResponse<Object> localVarResp = v1AffiliatesLinksInventorySummaryGetWithHttpInfo(groupBy);
        return localVarResp.getData();
    }

    /**
     * Inventory counts
     * Active/inactive link counts grouped by the requested dimension.
     * @param groupBy  (optional, default to operator)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> v1AffiliatesLinksInventorySummaryGetWithHttpInfo(@javax.annotation.Nullable String groupBy) throws ApiException {
        okhttp3.Call localVarCall = v1AffiliatesLinksInventorySummaryGetValidateBeforeCall(groupBy, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Inventory counts (asynchronously)
     * Active/inactive link counts grouped by the requested dimension.
     * @param groupBy  (optional, default to operator)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not permitted to access this resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> One or more fields failed validation; the message names each offending field. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Unexpected server error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1AffiliatesLinksInventorySummaryGetAsync(@javax.annotation.Nullable String groupBy, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1AffiliatesLinksInventorySummaryGetValidateBeforeCall(groupBy, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
